packages/elements/src/components/Docs/HttpOperation/Parameters.tsx
packages/elements/src/containers/API.stories.tsx

As confusing as it sounds, `sl-truncate` actually forces `white-space: nowrap;`. It makes some sense as `text-overflow: ellipsis` doesn't make much sense without a fixed-width, but still, we keep walking on this mine. I certainly do.
Of course this doesn't exactly make for a great user experience: 
Fortunately this has been fixed in JSV as well, so I just had to implement it for params. After:
I also added a few example APIs so we can test against them. (I picked the same ones Marc chose for the demo project, so the two are in sync).

fix: wrap parameter descriptions

---

packages/elements-web-components/package.json
packages/elements-web-components/src/index.ts

Fix(toc): missing caret icon in web components

---

renovate.json

We don't need to keep this config file anymore, as we decided to bump the lockfile ourselves using CircleCI workflow: #1090

chore: remove Renovate config file

---

cypress/integration/api.ts
cypress/integration/stoplight-project.ts
packages/elements/src/containers/API.tsx

Fixes: https://github.com/stoplightio/elements/issues/1129
Brings back mosaic provider to API component.
Adds simple e2e test to prevent that from happening in future.

fix: select dropdown

---

.circleci/config.yml

Recent failing of a workflow in CircleCI exposed an error in the config file. This PR addresses that, simply changing `--from-package`(which doesn't exist) to `from-package` (learn more at: https://github.com/lerna/lerna/tree/main/commands/publish#bump-from-package)

fix: incorrect lerna command in CirlcleCI job

---

packages/elements-dev-portal/package.json

This PR makes `elements-dev-portal` private for now, which should prevent the unwanted release from `lerna`.

fix: make elements-dev-portal private

---

demo/package.json
yarn.lock

Fixes the way `demo` is referencing `elements`. This change makes lerna recognize the relationship which in turn makes the lockfile a bit cleaner. Not much else to gain, but nothing to lose either.
cc @philsturgeon

chore: demo -> elements dependency

---

packages/elements/jest.config.js

This has the potential to resolve the spike at #1067 or at least provide clearer error messages.
**Important**
The timeout increase here is not a simple "let's give it more time" kind of bump. The problem I identified is that `testing-library`'s `waitFor` (and `findBy*`) timeout is 5 seconds, the same as Jest's default for timing out tests. This has the effect of running RTL-based continuations after the test env was torn down, leading to these ugly messages like
> ReferenceError: You are trying to access a property or method of the Jest environment after it has been torn down.
So at minimum, this should give us the real error messages (e.g. what `find*` actually times out).

test: increase timeout to prevent errors

---

examples/angular/src/app/stoplight-project/stoplight-project.component.ts
examples/react-cra/README.md
examples/react-cra/src/components/StoplightProject.tsx
examples/react-gatsby/src/pages/stoplight-project-demo.tsx
packages/elements-core/src/components/Docs/HttpService/__tests__/index.spec.tsx
packages/elements-core/src/containers/TableOfContents.stories.tsx
packages/elements-dev-portal/src/containers/StoplightProject.stories.tsx

Fixes: https://github.com/stoplightio/elements/issues/855
I've created `elements-examples` workspace (as `elements-demo` is taken by demo app) and pointed all our examples and docs there. All checked and point to right workspace.

chore: examples location

---

CONTRIBUTING.md
examples/bootstrap/index.html
packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.spec.tsx
packages/elements-core/src/utils/oas/security.ts
yarn.lock

I noticed this working with the Calendly description.
**Before**
https://elements-demo.stoplight.io/?spec=https://stoplight.io/api/v1/projects/calendly/api-docs/nodes/reference/calendly-api/openapi.yaml?branch=production#/operations/getUser
**After**
https://deploy-preview-1208--stoplight-elements-demo.netlify.app/?spec=https://stoplight.io/api/v1/projects/calendly/api-docs/nodes/reference/calendly-api/openapi.yaml?branch=production#/operations/getUser

fix: oauth 2.0 () when scopes empty

---

.github/dependabot.yml

Resolves #1140
As you can see, maintenance PRs have double scope now. This removes it.

chore: don't include scope

---

demo/src/components/ElementsAPI.tsx
package.json

Closes #1039 
Unfortunately the enablers decided to enforce the origin on the proxy so it doesn't work from localhost, you have to trust your code-reading abilities with this.

feat(demo): add CORS proxy functionality

---

packages/elements-core/package.json
scripts/build-styles.js

Add scss to elements-core build. Elements and elements-dev-portal are left with just css

feat: add scss to core build

---

examples/angular/package.json
examples/angular/yarn.lock

I just closed a dependabot PR in favor of this.
Does the upgrade to Angular 12 which is the current latest. Had to upgrade TS to 4.2 as well as it was a requirement.
Has a nice coincidence of making the pipeline faster by about 30 seconds as Angular 12 compiles faster and that was on the critical path. (I could remove the manual ngcc call as everything is Ivy by default.) Now it's equally fast/slow as CRA.

chore(angular): angular 12

---

packages/elements-core/src/components/Docs/HttpOperation/Badges.tsx
packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.tsx
packages/elements-core/src/components/Docs/Model/Model.tsx

Addresses #1325
Adds internal badge for endpoints marked as `x-internal`
Adds internal badge for models marked as `x-internal`
I also updated the layout so that the icon and text are aligned...I don't think this has a negative ripple effect anywhere, but I am not super familiar with Elements, so please let me know if I should undo this.

feat: internal badge

---

packages/elements-core/src/components/Docs/Docs.tsx
packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.spec.tsx
packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.tsx
packages/elements/src/components/API/APIWithSidebarLayout.tsx

Fixes: https://github.com/stoplightio/elements/issues/1333
Adds optional `allowRouting` prop to Docs that we can use with API component and which defaults to `false` for external usage.

fix: security badge link

---

packages/elements-core/src/styles/styles.scss

Currently, font size in JSV (description within a row) in models differs from JSV displayed for Http operation. This fixes that.
**Before**
**After**

fix: change font size in jsv for models

---

packages/elements-core/src/components/TryIt/TryIt.tsx

Resolves #1131 
Nothing too fancy. Unfortunately mosaic's `Link` doesn't have any default stying, so to still show that it may be clickable I applied the same semibold weight we used to have on there.

fix(try-it): contrast issue of CORS link

---

packages/elements-dev-portal/src/components/NodeContent/index.tsx

Fixes another issue reported by @philsturgeon for Qualtrics.
To test, open project with id `cHJqOjk3NDQ` in storybook. Before fix many urls in markdown documentation are not working (for example visit Overview > API General Instructions > Quickstart).
After fix links work.
The solution is necessary because backend provides encoded links in markdown, but decoded links in `outbound_edges` part of the response.

fix: resolving relative urls in dev portal

---

packages/elements-core/package.json
packages/elements-dev-portal/package.json
packages/elements-utils/package.json
packages/elements/package.json

We obviously don't support Node 10, just try
```sh
nvm use 10
yarn install --force
```
Also we shouldn't, it's pretty much EOL and SL doesn't use it either. So let's not advertise support for it because bumping this is technically a breaking change later.

chore: no(de) 10

---

packages/elements-core/src/components/Docs/HttpService/HttpService.spec.tsx
packages/elements-core/src/components/Docs/HttpService/HttpService.tsx
packages/elements-core/src/components/Docs/HttpService/ServerInfo.tsx

Resolves #1111 
More general than the issue: we would like to hide the box any time it would be empty, as an empty box looks broken.
To break it you can just use `https:///something` (note the triple forward slash).

feat(http-service): hide Base URL box when empty

---

packages/elements-core/package.json
yarn.lock

Related to: https://github.com/stoplightio/elements/pull/1426/files
Fixes react-cra build:
Before:
After:

fix: bump jsv to beta.22 (fixes react-cra)

---

examples/angular/src/app/stoplight-project/stoplight-project.component.ts
examples/react-cra/src/components/StoplightProject.tsx
examples/react-gatsby/src/pages/stoplight-project-demo.tsx
examples/static-html/stoplight-project/index.html
packages/elements-dev-portal/src/components/BranchSelector/BranchSelector.stories.tsx
packages/elements-dev-portal/src/components/NodeContent/NodeContent.stories.tsx
packages/elements-dev-portal/src/components/Search/Search.stories.tsx
packages/elements-dev-portal/src/components/TableOfContents/TableOfContents.stories.tsx
packages/elements-dev-portal/src/containers/StoplightProject.spec.tsx
packages/elements-dev-portal/src/containers/StoplightProject.stories.tsx
packages/elements-dev-portal/src/containers/StoplightProject.tsx
packages/elements-dev-portal/src/web-components/__stories__/StoplightProject.stories.tsx

Updates dev-portal `projectId` for storybook and examples as the current one no longer exists. 
New one comes from `https://elements-examples.stoplight.io` workspace.

fix: example project id

---

packages/elements-core/src/__fixtures__/operations/operation-with-examples.ts
packages/elements-core/src/components/ResponseExamples/ResponseExamples.spec.tsx
packages/elements-core/src/components/ResponseExamples/ResponseExamples.tsx
packages/elements-core/src/components/TryIt/useTextRequestBodyState.ts
packages/elements-core/src/utils/exampleGeneration.ts

fix: read/write only params in generated content

---

docs/getting-started/usage/layout.md
examples/angular/src/app/api/api.component.html
examples/angular/src/app/app.component.css
examples/angular/src/app/app.component.html
examples/angular/src/app/stoplight-project/stoplight-project.component.html
examples/bootstrap/index.html
examples/bootstrap/project.html
examples/react-cra/src/App.tsx
examples/react-cra/src/index.css
examples/react-gatsby/src/components/layout.css
examples/react-gatsby/src/components/layout.tsx
examples/static-html/index.html
examples/static-html/stoplight-project/index.html
examples/static-html/zoom-api/index.html
packages/elements-dev-portal/src/components/TableOfContents/TableOfContents.tsx

Resolves #1443 
This issue involves small fix in StoplightProject ToC layout, making it behave the same as API component.
If you run examples as copy (`copy:react-cra` etc.) and compare it to currently published examples, you will see that change.

chore: refactor examples layouts & fix stoplight toc layout

---

packages/elements-core/package.json
packages/elements-core/src/components/MosaicTableOfContents/utils.ts

Branched out from https://github.com/stoplightio/elements/pull/1483
Removing length check as added optional `version` property in elements service toc result makes it fail the check

fix: toc node check

---

packages/elements-core/package.json
packages/elements-core/src/components/MosaicTableOfContents/TableOfContents.tsx
packages/elements-core/src/styles/_TableOfContents.scss
packages/elements-core/src/styles/_main.scss
packages/elements-core/src/styles/elements.scss

Relates to https://github.com/stoplightio/platform-internal/issues/6900
This change should have no effect on how ToC looks in elements and dev-portal. Only related to platform.

fix: toc link colors in platform

---

.github/dependabot.yml
examples/angular/package.json
examples/react-cra/package.json

Fixes: https://github.com/stoplightio/elements/issues/1383
Dependabot got a recent [update](https://github.blog/changelog/2021-05-21-dependabot-version-updates-can-now-ignore-major-minor-patch-releases/) that allows to filter out bumps based on semver scope.
This PR makes it ignore all the patch and minor bumps leaving only major ones. The rest should be installed anyway in a latest version because of `^` usage.

chore: less noisy dependabot

---

packages/elements-core/src/components/Docs/HttpOperation/Badges.tsx
packages/elements-core/src/components/Docs/HttpService/HttpService.tsx
packages/elements-core/src/components/MosaicTableOfContents/TableOfContents.tsx
packages/elements-core/src/constants.ts

Fixes: https://github.com/stoplightio/elements/issues/1526
Brings back previous badges styles.

fix: badges

---

examples/react-gatsby/gatsby-node.js
examples/react-gatsby/package.json
packages/elements-core/package.json
yarn.lock

Fixes #1518 
- `process` and `util` are moved to elements-core dependencies. Those are peer dependencies of httpsnippet. Without them build doesn't work in environments which don't stub node.js modules themselves (like webpack 5).
- `jsdom` and `canvas` were required by markdown-viewer for SSR. I tested removing those packages and everything works, so it seems with new versions they are not necessary anymore.
- I also double-check our `gatsby-node` config and removed `http` and `https` stubs. I am not sure which library required those, but it seems that they are not needed anymore - everything works without them.

fix: gatsby dependencies and build process

---

packages/elements-core/package.json
packages/elements-core/src/components/MosaicTableOfContents/TableOfContents.spec.tsx
packages/elements-core/src/components/MosaicTableOfContents/utils.ts
packages/elements-dev-portal/package.json
packages/elements-dev-portal/src/version.ts

Addresses: stoplightio/platform-internal#6995 and follows https://github.com/stoplightio/elements/pull/1567
Ignores group nodes with an empty slug when searching for the first node. This way we can skip http services with no description (empty slug) and redirect to the next existing node. 
For testing in dev portal storybook you may use pr-env from linked platform PR:
platform URL: https://x-7031.stoplight-dev.com
https://user-images.githubusercontent.com/14196079/124975015-d1075180-e02d-11eb-844b-418f369a3a91.mov

fix(toc): find first node

---

.github/dependabot.yml

Followup to #1549 
This should hopefully solve the issue. 
IDK why the ignore approach wasn't working TBH, this is just a different - hopefully more supported - way of doing the same thing. What the `increase-if-necessary` strategy does is that it only changes `package.json` if the new package version falls out of the current range constraint. That should mean that wherever we have carets, we'll only get notified of major updates.

chore: quiet dependabot

---

packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.tsx
packages/elements-core/src/components/Docs/HttpService/HttpService.tsx
packages/elements-core/src/components/Docs/Model/Model.tsx
packages/elements-core/src/components/Docs/TwoColumnLayout.tsx
packages/elements-core/src/styles/_Docs.scss
packages/elements-dev-portal/src/components/NodeContent/NodeContent.tsx
yarn.lock

Fixes #1522
Few things I've done here:
- `TwoColumnsLayout` component unifies layouts on model, operation and overview pages.
- In `noHeading` mode components don't have any padding at the top - I believe this makes it easier to reason about components in separation.
- Font in model examples was changed using the same method as in `HttpOperation` page.
- In dev-portal I removed min-width on a model page

fix: model page layout

---

package.json
packages/elements-core/package.json
packages/elements-core/src/styles/_Docs.scss
packages/elements-dev-portal/package.json
packages/elements-dev-portal/src/version.ts
packages/elements/package.json
yarn.lock

Needed for: https://github.com/stoplightio/platform-internal/issues/7052
Also bumps `markdown-viewer` to `5.1.0`(this changes the `MarkdownViewer` components class, which affects the styling) - for details see: https://github.com/stoplightio/markdown-viewer/pull/100
Releases:
- `elements-core: 7.1.4 -> 7.1.5`
- `elements: 7.0.2 -> 7.0.3`
- `elements-dev-portal: 1.0.4 -> 1.0.5`

chore(release): elements-core v7.1.5

---

packages/elements-core/src/components/Layout/SidebarLayout.tsx
packages/elements-core/src/components/MosaicTableOfContents/TableOfContents.tsx
packages/elements-core/src/components/MosaicTableOfContents/types.ts
packages/elements-dev-portal/src/components/TableOfContents/TableOfContents.tsx
packages/elements-dev-portal/src/containers/StoplightProject.tsx
packages/elements/src/components/API/APIWithSidebarLayout.tsx

Fixes #1442 
You can test the behaviour in storybooks for `API` and `StoplightProject`, since those don't have limited height.
https://user-images.githubusercontent.com/7916523/125603360-6028431a-377c-4fa2-8015-ffd4eb4c8845.mov
Also fixes an additional problem - when loading a page ToC tries to scroll to the active element in the table of contents.
This is great when ToC has its own scroll, but bad when it doesn't - then the whole webpage is being scrolled to seemingly random places.

fix: scroll on toc click

---

.circleci/config.yml
.gitignore
package.json
packages/elements-core/jest.config.js
packages/elements-dev-portal/jest.config.js
packages/elements/jest.config.js
yarn.lock

Fixes: https://github.com/stoplightio/elements/issues/1301
Produces jest test result files and uploads them to CircleCI.
Cypress ones are already there.

chore: ci jest test results

---

packages/elements-core/package.json
packages/elements-core/src/components/MarkdownViewer/CustomComponents/Provider.tsx
packages/elements-core/src/index.ts

Needed for https://github.com/stoplightio/platform-internal/issues/7072
Adds elements-core missing exports that are used in platform

fix: add missing exports

---

packages/elements-core/src/styles/_HttpOperation.scss

Resolves: #1614
One of the recent MarkdownViewer releases changed the `.MarkdownViewer` class to `.sl-markdown-viewer`. We use this classes for styling, and this PR addresses the change
**Before**
**After**

fix: Query param description have larger fontsize than expected

---

packages/elements-core/package.json
packages/elements-core/src/hooks/useComputeMarkdownHeadings.ts
packages/elements-core/tsconfig.build.json
packages/elements-core/tsconfig.json
packages/elements-dev-portal/package.json
packages/elements-dev-portal/src/version.ts
packages/elements-dev-portal/tsconfig.build.json
packages/elements-dev-portal/tsconfig.json
packages/elements-utils/package.json
packages/elements-utils/tsconfig.build.json
packages/elements-utils/tsconfig.json
packages/elements/package.json
packages/elements/tsconfig.build.json
packages/elements/tsconfig.json
yarn.lock

Fixes: https://github.com/stoplightio/elements/issues/1392
Builds ES module along with CJS using sl-scripts bundling. 
Adds `styles.min.css` to exports to include it in the encapsulated bundle.
Tested with examples and platform (requires replacing deep imports for elements-core).

chore: create ES module build

---

packages/elements-core/src/components/MarkdownViewer/CustomComponents/CodeComponent.tsx
packages/elements-core/src/components/MarkdownViewer/CustomComponents/Provider.tsx
packages/elements-core/src/index.ts

~status: currently yalcing it into a platform-internal branch to confirm it works as expected~
~fuck it, the dependency graph in platform-internal is just too dang complicated to get yalcing it to work with yarn resolutions AFAICT:~
~oh oh wait, I might have figured it out. looks like it's called `generateClassicToC` now... testing it out now..~
I give up yalcing. Let's just merge and publish this if it seems like it won't hurt.

feat: export DefaultSMDComponents

---

packages/elements-dev-portal/src/containers/StoplightProject.tsx

Fixes: https://github.com/stoplightio/elements/issues/1524
ToC groups are initialized during the first render when data might not yet be fetched, which causes `activeId` to be undefined and a group collapsed. Using node id from node slug (which we know already) fixes the issue.

fix: expand node when child is active

---

.circleci/config.yml
examples/react-gatsby/package.json
packages/elements-core/package.json
packages/elements-dev-portal/package.json
yarn.lock

Fixes gatsby build by:
- bumping MDV
- using node >=14.13 for cypress workflow - gatsby has a dependency that requires usage of node in version >=12.20 which is missing in cypress docker images. 
Looks like @marcelltoth first approach in https://github.com/stoplightio/elements/pull/1653 was correct.

fix: gatsby build

---

packages/elements-core/src/__fixtures__/operations/put-todos.ts
packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.spec.tsx
packages/elements-core/src/components/Docs/HttpOperation/Parameters.tsx
packages/elements/package.json
yarn.lock

Closes https://github.com/stoplightio/platform-internal/issues/6720 and https://github.com/stoplightio/elements/issues/1032
Makes sure that `parameter.example`, `parameter.examples` and `parameter.schema.examples` are displayed correctly.
Doesn't display `parameter.schema.example`, since it doesn't exist on the typings nor is mentioned in JSON Schema docs - https://json-schema.org/understanding-json-schema/reference/generic.html
Unifying `parameter.example` and `parameter.examples` was done in `http-spec`, hence it is not visible in tests here. That's what `http-spec` update is for.

fix: openapi and schema examples validations rendering

---

packages/elements-core/src/components/Docs/Docs.tsx
packages/elements-core/src/components/Docs/HttpService/ExportButton.tsx
packages/elements-core/src/components/Docs/HttpService/HttpService.spec.tsx
packages/elements-core/src/components/Docs/HttpService/HttpService.tsx
packages/elements-core/src/index.ts
packages/elements-dev-portal/src/components/NodeContent/NodeContent.tsx
packages/elements-dev-portal/src/containers/StoplightProject.tsx
packages/elements-dev-portal/src/web-components/components.ts
packages/elements/package.json
packages/elements/src/__fixtures__/api-descriptions/todosApiBundled.ts
packages/elements/src/components/API/APIWithSidebarLayout.tsx
packages/elements/src/components/API/APIWithStackedLayout.tsx
packages/elements/src/containers/API.tsx
packages/elements/src/hooks/useExportDocumentProps.spec.tsx
packages/elements/src/hooks/useExportDocumentProps.tsx
packages/elements/src/utils/oas/index.ts
packages/elements/src/web-components/components.ts
yarn.lock

Fixes: https://github.com/stoplightio/elements/issues/707
Requires https://github.com/stoplightio/platform-internal/pull/7315 to make export button visible in StoplightProject (it's on v2 but not yet in prod)
Adds export/download feature to API and StopolightProject components.

feat: openapi export

---

packages/elements-core/package.json
packages/elements-dev-portal/package.json
packages/elements-utils/package.json
packages/elements/package.json

- @stoplight/elements-core@7.1.11
- @stoplight/elements-dev-portal@1.0.9
- @stoplight/elements@7.0.6
- @stoplight/elements-utils@7.0.1
**Changes:**
fix: reduce react query cache time (#1607)
chore: folderize tryit (#1609)
chore: ci jest test results (#1611)
fix: add missing exports (#1629)
fix: use sl-markdown-viewer class for styling (#1628)
chore: create ES module build (#1625)
chore: no scss (#1624)
feat: export DefaultSMDComponents (#1633)
chore(release): core release (#1637)
chore: utils cleanup (#1631)
feat: dont retry failed requests (#1642)
fix: uppercase request method (#1641)
fix: always show overview page in API component (#1639)
chore: webpack 4 -> 5 migration (#1640) 
chore: no description overview cleanup (#1645)
fix: update request samples when mocking (#1644)
chore: weekly …

chore: release

---

packages/elements-core/src/components/Docs/Model/Model.spec.tsx
packages/elements-core/src/components/Docs/Model/Model.tsx
packages/elements-dev-portal/src/components/NodeContent/NodeContent.tsx
packages/elements-dev-portal/src/version.ts
packages/elements/src/components/API/APIWithSidebarLayout.tsx

Fixes: https://github.com/stoplightio/elements/issues/1658
Adds export button for standalone models in DevPortal.
It doesn't make sense to export models in API component since they are embedded into API document itself.

feat: models export button

---

packages/elements-core/src/components/Docs/Article/index.tsx
packages/elements-core/src/styles.css
packages/elements-dev-portal/src/styles.css

A part of: https://github.com/stoplightio/elements/issues/1618
This adds some class names to the `Docs/Article` component and later applies custom styling to this component in `elements-dev-portal`. I decided not to modify the `Article` component directly in order to make it more customizable for other usages.
**Before**
https://user-images.githubusercontent.com/58433203/128506785-cd574528-1501-4fc8-9ac8-d723a9c66efe.mov
**After**
https://user-images.githubusercontent.com/58433203/128506554-fefa9215-f744-45cc-948f-971cb5d27a75.mov

Fix: increase padding in docs

---

packages/elements-core/src/components/Docs/Model/Model.spec.tsx
packages/elements-core/src/components/Docs/Model/Model.tsx

Addresses #7386
Gets rid of duplicate description for schemas that aren't objects. 
If data.type is an object, should show description. If it's not, don't show description. 
vs.

chore: don't show duplicate schema description for non-objects

---

packages/elements-core/src/styles.css

Resolves #1562 
Also fixes some broken CSS that still has the old classname (`MarkdownViewer` instead of `sl-markdown-viewer`).

fix: jsv padding

---

packages/elements-core/src/components/MarkdownViewer/CustomComponents/CodeComponent.spec.ts
packages/elements-core/src/components/MarkdownViewer/CustomComponents/CodeComponent.tsx
yarn.lock

A part of: https://github.com/stoplightio/platform-internal/issues/7388
This PR adds a posibility to enter the value of path parameters, which are now available in inline TryIt/RequestMaker (in MarkdownViewer) based on the names extracted from url e.g.
```
$baseUrl/hello/{param1}/welcome/{path2}
```
Will allow to pass values for `param1` and `param2`
All of this is utilizing and modifying existing `parseHttpRequest` function which expects data of type `PartialHttpRequest` - path parameters are not specified there per se, as they normaly are in OAS document (where you need path param both in url and a corresponding path param object).
There's a limitation here that we only allow to pass values, but do not show examples, expected data format (`string`, `number`, etc.) or prepopulate the …

feat: In MarkdownViewer TryIt, parse path parameters based on provided url

---

.circleci/config.yml

Normally this doesn't matter, but I wanted to be able to "re-run" failed lockfile maintenance jobs, in which case it matters that you're running on the latest commit.

chore: weekly maintenance PR should always run on latest 'main' commit

---

packages/elements-core/src/components/Docs/HttpService/HttpService.spec.tsx
packages/elements-core/src/components/Docs/HttpService/SecuritySchemes.tsx

Addresses [#7586](https://app.zenhub.com/workspaces/-team-pierogi-platoon-610871b8d6e5310013071b72/issues/stoplightio/platform-internal/7586)
When a custom description is added to a security scheme, it shows that description as well as other existing information.

chore: show description and other scheme details

---

packages/elements-core/package.json
packages/elements-dev-portal/package.json
yarn.lock

Related to [#7591](https://app.zenhub.com/workspaces/-team-pierogi-platoon-610871b8d6e5310013071b72/issues/stoplightio/platform-internal/7591)
Before:
After:

chore: bump markdown viewer version

---

packages/elements-core/src/components/RequestSamples/RequestSamples.tsx
packages/elements-core/src/components/TryIt/Body/RequestBody.tsx

Should address #1664 specifically request sample panel was unnecessarily long. Request body looks to already be fixed.
before: 
after:

fix: maxHeight for panels

---

packages/elements-core/package.json
packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.spec.tsx
yarn.lock

Fixes: https://github.com/stoplightio/platform-internal/issues/7377
Bumps JSV to include this [change](https://github.com/stoplightio/json-schema-viewer/pull/162)

feat: unquote validations

---

packages/elements-core/src/__fixtures__/operations/base64-file-upload.ts
packages/elements-core/src/__fixtures__/operations/multipart-formdata-post.ts
packages/elements-core/src/components/TryIt/Body/request-body-utils.ts
packages/elements-core/src/components/TryIt/Parameters/parameter-utils.ts

Closes #1649 
Test with yaml:
```
openapi: 3.0.0
info:
title: Some API
description: This is a description
contact:
email: some@email.com
version: 1.0.0
servers:
- url: '/v1/api'
description: Develop
tags:
- name: media
paths:
/media:
post:
operationId: create_media
tags:
- media
summary: Create media
security:
- API Key: []
requestBody:
content:
multipart/form-data:
schema:
type: object
properties:
metadata:
type: string
image:
type: string
format: binary
encoding:
image:
contentType: image/png, image/jpeg
responses:
'200':
description: |
Media created successfully.
content:
application/json:
schema:
type: string
components:
securitySchemes:
API Key:
name: x-api-key
type: apiKey
in: header
security:
- API Key: []
```
Reasoning for change:
Http-spec library is transforming binary and …

fix: file upload

---

packages/elements-core/src/components/MosaicTableOfContents/TableOfContents.tsx
packages/elements-core/src/components/MosaicTableOfContents/types.ts
packages/elements-dev-portal/src/components/TableOfContents/TableOfContents.tsx

Addresses: https://github.com/stoplightio/platform-internal/issues/7661
ToC in the platform doesn't use its own scrollbar like the elements or elements-dev-portal version, it rather uses higher-level one. This means that the default mechanism to detect whether ToC is using scrollbar doesn't affect here. 
This PR adds an optional property to ToC to indicate that there's an external scrollbar and we can scroll to active item.
Platform PR will need to add that property to ToC container.

fix: external scrollbar

---

packages/elements-core/package.json
yarn.lock

For #1665
JSV PR: https://github.com/stoplightio/json-schema-viewer/pull/163
I've tested it using elements storybook, by adding `test` property in `User` schema
```yaml
test:
type: array
items:
enum: 
- p1
- p2
- p3
```
**Before**
**After**

chore: bump JSV version

---

packages/elements-core/src/components/Docs/Docs.tsx
packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.tsx
packages/elements-core/src/components/TryIt/TryIt.spec.tsx
packages/elements-core/src/components/TryIt/TryIt.tsx
packages/elements-core/src/components/TryIt/build-request.ts
packages/elements-dev-portal/src/components/NodeContent/NodeContent.tsx
packages/elements-dev-portal/src/containers/StoplightProject.tsx
packages/elements-dev-portal/src/web-components/components.ts
packages/elements/src/components/API/APIWithSidebarLayout.tsx
packages/elements/src/components/API/APIWithStackedLayout.tsx
packages/elements/src/containers/API.tsx
packages/elements/src/web-components/components.ts

Addresses https://github.com/stoplightio/elements/issues/1548 
Based on @haseebeqx PR at https://github.com/stoplightio/elements/pull/1585
Adds support for setting credential policy in TryIt by adding the optional `tryItCredentialsPolicy` property.
@haseebeqx your PR is great, thanks for contribution. I've moved it here so it's not based on the fork and did some small changes:
- added similar property for `elements-dev-portal`
- removed redundant `tryItCredentialsPolicy` from `StackedLayout` - we're using TryIt separately there
- setting default value to `omit` in `build-request`
- added basic tests

feat: tryit credentials policy

---

examples/angular/package.json
packages/elements-core/src/components/MarkdownViewer/CustomComponents/CodeComponent.tsx
packages/elements-core/src/components/RequestSamples/RequestSamples.tsx
packages/elements-core/src/components/TryIt/TryIt.spec.tsx
packages/elements-core/src/components/TryIt/TryIt.tsx

Attempts to address #[7389](https://app.zenhub.com/workspaces/-team-pierogi-platoon-610871b8d6e5310013071b72/issues/stoplightio/platform-internal/7389)
The codegen panel is now sandwiched between the request and the response per this [figma](https://www.figma.com/file/IaSAr7tMvF9JSUz6bQ7cX3/Codegen?node-id=0%3A1) design
I am not sure if I actually solved this because I'm not super familar with how all of these components work together, but I tried to get it to look as close to the figma design as possible. 
Also, Angular build for e2e was not working due to typescript version, so I updated it to play nicely, but not sure if that is an okay longterm solution.

feat: add codegen to embedded request maker

---

packages/elements-core/package.json
packages/elements-core/src/utils/exampleGeneration.ts

For https://github.com/stoplightio/platform-internal/issues/7698
`x-examples` can be defined with and without `value` and both should be supported:
```json
{
"title": "User",
"type": "object",
"description": "",
"x-examples": {
"Alice Smith": {
"id": 142,
"firstName": "Alice",
"lastName": "Smith",
"email": "alice.smith@gmail.com",
"dateOfBirth": "1997-10-31",
"emailVerified": true,
"signUpDate": "2019-08-24"
},
"example-2": {
"value": {
"id": 0,
"firstName": "n",
"lastName": "string",
"email": "user@example.com",
"dateOfBirth": "1997-10-31",
"emailVerified": true,
"createDate": "2019-08-24"
}
},
},
"properties": {
"id": {
"type": "integer",
"description": "Unique identifier for the given user."
},
"firstName": {
"type": "string"
},
"lastName": {
"type": "string"
},
"email": {
"type": …
```

fix: support examples with and without value prop

---

cypress/integration/stoplight-project.ts
packages/elements-core/package.json
packages/elements-core/src/components/TryIt/Response/Response.spec.tsx
packages/elements-core/src/components/TryIt/Response/Response.tsx
packages/elements-core/src/components/TryIt/TryIt.tsx
yarn.lock

Addresses: https://github.com/stoplightio/elements/issues/649
Adds response body format (`Preview`, `Raw`) support depending on `content-type`.
Adds support for displaying response images.
I've moved the `Response` component to a separate file as it got too big. Some parts of it remain the same but there's plenty added.
https://user-images.githubusercontent.com/14196079/131678365-d45f2004-ee4b-4b10-955a-198de868061b.mov
https://user-images.githubusercontent.com/14196079/131678387-aba61b53-24cb-433f-b291-dc78f51d4e8d.mov
https://user-images.githubusercontent.com/14196079/131679073-10c7c426-bc69-4184-bc77-b477ab419110.mov
https://user-images.githubusercontent.com/14196079/131679092-c43b4bca-9e45-43cd-9cc1-d0ecd5a4d264.mov

feat: response body format and images

---

packages/elements-dev-portal/src/hooks/useGetNodes.ts

A part of https://github.com/stoplightio/platform-internal/pull/8024
This allows to put the `useGetNodes` in the `idle` state when we explicitly tell it to (more about pausing queries in https://react-query.tanstack.com/guides/disabling-queries)
We could of course make the hook be in `idle` until `search` isn't falsy but this would change the current, default behavior of this hook. With this change we don't, you need to explicitely state if you want to pause the query or not. I was trying to mimick the behavior of `urql(..., { pause })` option

feat: allow pausing getNodes query by passing prop

---

packages/elements-dev-portal/package.json

Release:
- `elements-dev-portal`: 1.4.0
fix: remove unnecessary logic (#1774)
feat: allow pausing getNodes query by passing prop (#1773)

chore: release elements-dev-portal 1.4.0

---

packages/elements-core/src/components/TryIt/TryIt.spec.tsx
packages/elements-core/src/components/TryIt/build-request.ts

Addresses https://github.com/stoplightio/platform-internal/issues/7851
The bug was occurring because we were including `content-type` header to every fetch request. The result, in this case, was`multipart/form-data` with no boundary which was failing. 
The solution is to not include content type at all and let browser handle it along with the boundary.

fix: skip content type for multipart request

---

packages/elements-core/package.json
packages/elements-core/src/utils/exampleGeneration.ts
yarn.lock

Addresses #[7923](https://app.zenhub.com/workspaces/-team-pierogi-platoon-610871b8d6e5310013071b72/issues/stoplightio/platform-internal/7923)
Before: page becomes unresponsive when clicking around to models with circular refs
After:

fix: allow large specs to load schema

---

packages/elements-core/src/__fixtures__/operations/multipart-formdata-post.ts
packages/elements-core/src/__fixtures__/operations/put-todos.ts
packages/elements-core/src/__fixtures__/operations/request-body.ts
packages/elements-core/src/__fixtures__/operations/urlencoded-post.ts
packages/elements-core/src/components/TryIt/Body/FormDataBody.tsx
packages/elements-core/src/components/TryIt/Body/request-body-utils.ts
packages/elements-core/src/components/TryIt/Parameters/parameter-utils.spec.ts
packages/elements-core/src/components/TryIt/Parameters/parameter-utils.ts
packages/elements-core/src/components/TryIt/TryIt.spec.tsx
packages/elements-dev-portal/src/handlers/getTableOfContents.ts

Addresses: https://github.com/stoplightio/platform-internal/issues/7664
Removes default value from optional enum parameters.
Adds `required` property when mapping from JsonSchema to OpenApi parameter schema.
Simple API document for testing: [api](https://github.com/stoplightio/platform-internal/files/7016097/5547.zip)

fix: default values for optional parameters

---

packages/elements-core/src/components/TryIt/Mocking/mocking-utils.ts
packages/elements-core/src/components/TryIt/TryIt.spec.tsx

Addresses https://github.com/stoplightio/elements/issues/1757
Prevents adding `Prefer` header when no mocking options are selected

fix: do not include prefer header with no mock data

---

packages/elements/src/containers/API.stories.tsx

I've noticed that some fields in storybook are not displayed properly, which makes testing and debugging a bit more difficult (at least for me):
Before:
After:

fix: apiDescriptionDocument input in storybook

---

packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.spec.tsx
packages/elements-core/src/components/Docs/HttpOperation/Parameters.spec.tsx
packages/elements-core/src/components/Docs/HttpOperation/Parameters.tsx

Resolves: #1750
Enables `Elements` to display enum definitions places in `schema/items/enum`. Until now only `schema/enum` was supported. We are now also displaying array subtype for request parameters.
I've also added unit tests, and updated some existing ones.
Testing schema for OAS3 and OAS3.1 (put it in `paths/parameters` in API document):
```json
{
"description": "An array query parameter",
"in": "query",
"name": "enum_array",
"required": false,
"schema": {
"description": "An array query parameter",
"items": {
"enum": [
"foo",
"bar"
],
"type": "string"
},
"type": "array"
}
}
```

Fix: Missing array enum item definitions in query parameters

---

packages/elements-core/.storybook/preview.jsx
packages/elements-core/src/components/MarkdownViewer/CustomComponents/Provider.tsx

Addresses: https://github.com/stoplightio/platform-internal/issues/8048
Addresses: https://github.com/stoplightio/platform-internal/issues/8047
When [cleaning up](https://github.com/stoplightio/elements/pull/1754/files) markdown viewer providers we didn't add custom code component, and markdown viewer doesn't provide it itself. The result was that the default code component was used and both `json_schema` and `http` types weren't there.
This PR adds code component to provider default props and makes `elements-core` storybook use it. 
`elements-dev-portal` is already using that provider in `NodeContent` so no need to change anything there.

fix: use custom code component in mdv provider

---

packages/elements/package.json

releases fix for: https://github.com/stoplightio/elements/issues/1805.
PR that it releases is: https://github.com/stoplightio/elements/pull/1830

chore: release 7.3.8

---

packages/elements-core/package.json
yarn.lock

Addresses: https://github.com/stoplightio/platform-internal/issues/8463
Bumps `json-schema-viewer`.
Fixes merging nested `allOf` combiners where titles were always picked from the last element making schemas with nested `allOf`s have incorrect titles.
Example of api document with mentioned nested combiners:
```
openapi: 3.1.0
info:
title: Combiners
version: '1.0'
servers:
- url: 'http://localhost:3000'
paths:
/user:
get:
summary: Get user
operationId: get-user
responses:
'200':
description: OK
content:
application/json:
schema:
anyOf:
- allOf:
- type: object
properties:
test:
type: string
- $ref: '#/components/schemas/User'
- allOf:
- type: object
properties:
test:
type: string
- $ref: '#/components/schemas/Account'
components:
schemas:
User:
title: User
description: ''
examples:
- id: …
```

fix: merging titles in schemas with nested allofs

---

packages/elements-core/src/components/TryIt/Parameters/parameter-utils.ts
packages/elements-dev-portal/src/components/Search/Search.tsx
packages/elements-dev-portal/src/containers/StoplightProject.tsx
packages/elements-utils/src/toc/toc.ts
packages/elements/src/containers/API.spec.tsx
packages/elements/src/containers/API.tsx

Resolves: #1809
Replaces `lodash/fp` methods with those from `lodash`

chore: remove lodash/fp methods

---

packages/elements-core/package.json
packages/elements-dev-portal/package.json
packages/elements-utils/package.json
packages/elements/package.json

elements-core: `7.3.9` -> `7.3.10`
elements: `7.3.10` -> `7.3.11`
elements-dev-portal: `1.4.6` -> `1.4.7`
elements-utils: `7.1.1` -> `7.1.2`
- chore: remove lodash/fp methods (#1850)

chore: release elements

---

packages/elements-core/src/components/MosaicTableOfContents/types.ts
packages/elements-core/src/index.ts
packages/elements-dev-portal/src/components/NodeContent/NodeContent.tsx
packages/elements-dev-portal/src/containers/StoplightProject.tsx
packages/elements-dev-portal/src/version.ts

Addresses #8606
Anchor tags were not appended to links if those links were pointing to another document. Links are now appended, but scrolling to the anchor position is not working. This seems to be a known bug when using react-router-dom:
https://github.com/remix-run/react-router/issues/394#issuecomment-220221604
To test:
Option 1:
1. Checkout branch
2. Create two articles. In one article, create a top header and a bottom header located somewhere else down the page.
2. In your second article, link to the top header and the bottom header.
3. You will notice the anchor tags are appended to the outbound links, but the scrolling to the anchor position is not working
https://user-images.githubusercontent.com/52048026/141879149-60a7b490-56f6-417c-a4bc-2d75f7090e9f.mov
Option 2:
1. Checkout …

fix (elements-dev-portal): anchor tags stripped from uri

---

packages/elements-core/src/hoc/withMosaicProvider.spec.tsx
packages/elements-core/src/hoc/withMosaicProvider.tsx
packages/elements-core/src/hoc/withQueryClientProvider.spec.tsx
packages/elements-core/src/hoc/withQueryClientProvider.tsx
packages/elements-dev-portal/src/components/DevPortalProvider/index.tsx

If the application that elements is embedded into is already using mosaic or react-query, re-use those contexts rather than creating new ones.
Particularly applicable to platform - as it stands now we are creating excess contexts, and not respecting the options set on the parent contexts.

fix: reuse mosaic, react-query context if possible

---

.eslintrc.js
demo/src/constants.ts
packages/elements-core/package.json
packages/elements-core/src/components/Docs/HttpOperation/Request.tsx
packages/elements-core/src/components/Docs/HttpService/SecuritySchemes.tsx
packages/elements-core/src/components/MarkdownViewer/CustomComponents/CodeComponent.tsx
packages/elements-core/src/components/MarkdownViewer/CustomComponents/Provider.tsx
packages/elements-core/src/components/TryIt/Parameters/parameter-utils.ts
packages/elements-core/src/components/TryIt/Response/Response.tsx
packages/elements-core/src/index.ts
packages/elements-core/src/utils/securitySchemes.ts
packages/elements-dev-portal/package.json
packages/elements-dev-portal/src/components/Search/Search.tsx
packages/elements-utils/package.json
packages/elements/package.json
yarn.lock

Adjustments such that the build output can be used in mjs environments such as NextJS v12.
- chore(demo): fix linode spec link
- fix: circular import
- fix: do not use `_.chain`, mjs compat and it breaks tree-shaking
- fix: root FA/lodash imports for mjs compat (also added an eslint rule to enforce this pattern)

fix(build): mjs/nextjs 12/swc compatibility

---

packages/elements-core/src/utils/exampleGeneration/exampleGeneration.ts

This `console.error` call heavily pollutes Sentry.
We don't really need to call `console.error`, as in most cases it's an error on the user end. Moreover, the message is displayed to the end-user, therefore they know that an error occurred without looking into the console.

chore(core): do not log example generation failures

---

packages/elements-core/package.json
yarn.lock

For stoplightio/platform-internal#9043
Oas with models that have boolean values like:
```yaml
properties:
createDate:
type: object
properties:
mmm:
type: boolean
default: true
nnn:
type: boolean
default: false
example: true
```
Now show up as `default value: true` and `example value: true` and before it showed `Default` and `Examples` and nothing at all if the value was `false`

fix: bump JSV for properly showing boolean values

---

packages/elements-dev-portal/src/components/Search/Search.stories.tsx
packages/elements-dev-portal/src/components/Search/Search.tsx
packages/elements-dev-portal/src/hooks/useGetNodes.ts

Follow up to https://github.com/stoplightio/elements/pull/1880. Feel free to copy the changes to that PR too.
- Add loading spinner in place of search icon while fetching/loading
- Add `keepPreviousData` to `useGetNodes` hook to keep previous search data while we're searching

feat(DevPortal): search loading indicator

---

.github/dependabot.yml

Relates to #1886 
Currently dependant spams us with angular 12 -> 13 updates on a weekly basis.
This PR makes them more rare.
To be reverted once #1886 is done.

chore: make angular dependabot updates more rare

---

packages/elements-core/src/components/Docs/HttpOperation/Body.tsx
packages/elements-core/src/components/Docs/HttpOperation/Responses.tsx
packages/elements-dev-portal/src/version.ts

Removal of hideExamples prop allows for the examples in studio to be shown.
To test:
1. Create an API style guide in studio. 
2. In properties, type a string
3. In JSV, your example should be shown
**NOTE:** I can provide a branch to the yalc'd `elements-core` into platform if needed

 fix(elements-core): removed hideExamples prop

---

packages/elements-core/src/__fixtures__/articles/kitchen-sink.md
packages/elements-core/src/__fixtures__/articles/multiple-try-its.md
packages/elements-core/src/components/MarkdownViewer/CustomComponents/CodeComponent.spec.ts
packages/elements-core/src/components/MarkdownViewer/CustomComponents/CodeComponent.tsx
packages/elements-core/src/components/MarkdownViewer/MarkdownViewer.spec.tsx

Fixes https://github.com/stoplightio/platform-internal/issues/9443
-  If a default value is provided with the embedded request maker, we will now mark it as required so the default value will be set.
- Update "multiple try it" storybook example to be a realistic use case. Can see "api_key" default is now set automatically

fix(embedded-tryit): require parameter when a default is provided

---

packages/elements-core/src/__fixtures__/operations/string-numeric-enums.ts
packages/elements-core/src/components/TryIt/Parameters/parameter-utils.ts
packages/elements-core/src/components/TryIt/TryIt.spec.tsx

Addresses: https://github.com/stoplightio/platform-internal/issues/7868
Fixes parsing string numeric enums

fix(try-it): numeric enums

---

packages/elements-core/src/__fixtures__/operations/put-todos.ts
packages/elements-core/src/components/TryIt/TryIt.spec.tsx
packages/elements-core/src/components/TryIt/build-request.ts

Addresses: https://github.com/stoplightio/platform-internal/issues/9109
Filters out optional headers with no value provided when building request

fix(try-it): empty optional headers

---

packages/elements-core/package.json

Bumps JSV to address [9513](https://app.zenhub.com/workspaces/-team-pierogi-platoon-610871b8d6e5310013071b72/issues/stoplightio/platform-internal/9513)
Here's a screenshot from elements-core storybook as sanity check:

chore: bump jsv to show more combiners

---

yarn.lock

forgot to run `yarn` when bumping JSV in https://github.com/stoplightio/elements/pull/1961

chore: yarn lock for jsv bump

---

packages/elements-core/src/__fixtures__/operations/put-todos.ts
packages/elements-core/src/components/TryIt/Parameters/parameter-utils.ts
packages/elements-core/src/components/TryIt/TryIt.spec.tsx

Addresses https://github.com/stoplightio/elements/issues/1857
The reason for elements breaking was a quote in one of the examples: `FF_SEGMENT_RPT_LABELS("ANN_R",0,-1AY,BUS,SEG)` which crashes in mosaic Select due to failure in executing query selector for `data-key="{value_with_quote}"` property.
Escaping quotes (just like in JSV) makes it work. The downside is that it changes the original value. 
Another solution could be escaping it only for the Select component and resetting the original value after selecting but that might be a bit over-engineered way.

fix(try-it): escape quotes in parameter examples

---

packages/elements-dev-portal/src/handlers/__tests__/getBranches.test.ts
packages/elements-dev-portal/src/handlers/__tests__/getNodeContent.test.ts
packages/elements-dev-portal/src/handlers/__tests__/getNodes.test.ts
packages/elements-dev-portal/src/handlers/__tests__/getTableOfContents.test.ts
packages/elements-dev-portal/src/handlers/__tests__/getWorkspace.test.ts
packages/elements-dev-portal/src/handlers/getBranches.ts
packages/elements-dev-portal/src/handlers/getNodeContent.ts
packages/elements-dev-portal/src/handlers/getNodes.ts
packages/elements-dev-portal/src/handlers/getTableOfContents.ts
packages/elements-dev-portal/src/handlers/getWorkspace.ts

This fixes places where the platform URL components were only concatenated and not encoded. I separated out the encoded variables in order to maintain readability of the interpolated string

fix: encode uri components before calling platform

---

packages/elements-dev-portal/src/components/NodeContent/NodeContent.tsx

@jgreen44 pointed me to the line. I'm like, 95% confident this will fix #1969.
Update: I have tested it by yalcing dev portal into platform-internal and confirm it does the trick.

fix: don't add "undefined" to the end of links

---

packages/elements-core/src/components/TryIt/Response/Response.spec.tsx
packages/elements-core/src/components/TryIt/Response/Response.tsx

For: https://github.com/stoplightio/platform-internal/issues/9446
It can be reproduced by using this [spec](https://stoplight.io/api/v1/projects/kontakt-api-docs/dev-ctr-device-api/nodes/spec10.json) (with api key in issue) but I've also added a speed test for that function

fix: responseType slow regex check

---

packages/elements-core/src/components/Docs/Docs.tsx
packages/elements-dev-portal/src/components/NodeContent/NodeContent.tsx

For [stoplightio/platform-internal/8677](https://github.com/stoplightio/platform-internal/issues/8677)
Connected PR: https://github.com/stoplightio/platform-internal/pull/9882
Adds ability to pass a custom `refResolver` function in `NodeContent` and `Docs`

chore: refResolver param in Docs and NodeContent

---

packages/elements-core/package.json
packages/elements-core/src/components/MarkdownViewer/CustomComponents/CodeComponent.tsx
packages/elements-dev-portal/package.json
packages/elements/package.json
yarn.lock

~Needs https://github.com/stoplightio/markdown-viewer/pull/114~
Needed by https://github.com/stoplightio/platform-internal/pull/9586
Use the `resolved` property if it exists on the MDAST tree.
This allows us to display the resolved schema when embedded in markdown (see image)

fix(embedded-jsv): use resolved value if one exists in the markdown tree

---

packages/elements-core/src/utils/guards.ts
packages/elements-core/src/utils/http-spec/IServer.ts
packages/elements-core/src/utils/http-spec/__tests__/IServer.spec.ts

Fixes https://github.com/stoplightio/platform-internal/issues/9800
According to [RFC3986#3.2.2](https://www.rfc-editor.org/rfc/rfc3986#section-3.2.2), which OAS spec adheres to, `[` and `]` are not valid chars to use as a host.
I'm uncertain how to handle https://github.com/stoplightio/elements/blob/9f9ae13782edde922f4299a3db817a545095aa55/packages/elements-core/src/components/TryIt/build-request.ts#L44L45 from the UX standpoint.
If the URL is invalid, we'll end up using the current origin of the active frame elements is embedded in, which might be a potentially jarring experience. 
Either way, since this is likely uncommon to happen, we may be good to leave it as is.

fix(core): gracefully handle invalid URLs in server objects

---

packages/elements-core/src/components/TryIt/TryIt.tsx
packages/elements-core/src/components/TryIt/build-request.ts

Addresses: [#9966](https://github.com/stoplightio/platform-internal/issues/9966)
**Summary**
Endpoints that had trailing slashes (ex. /user/) were returning a response of 422 (sometimes). This was because the trailing slash was being stripped out, ultimately pointing to either a non-existent path, or in an edge-case, to the wrong path (ex. /user). This edge-case was returning a response of 200. Allowing the use of a trailing slash now points to two paths if necessary (/user and /user/).
**Steps to Test**
1. Create API project in local or prod with both use-cases:
a. With endpoint /user
b. With endpoint /user/
2. Run storybook in elements-dev-portal
3. Copy nodeSlug, projectId from newly created API project (step 1)
4. Paste values into Storybook and use https://stoplight.io (if step 1 is …

fix(elements-core): allow trailing slash use for endpoints

---

packages/elements-dev-portal/src/components/NodeContent/NodeContent.tsx

This change allows one to link into an operation or schema that is defined in an openapi specification, along the lines of `[My link to a specific http operation](/reference/openapi.json/paths/~1v2~1contact~1last_change/post)`.

fix(dev-portal): support links to http operations

---

docs/getting-started/dev-portal/react.md
docs/getting-started/elements/react.md

Partially addresses https://github.com/stoplightio/elements/issues/2058.
We're still looking into alternatives to CRA such as:
- [Create Next App with `-e`](https://nextjs.org/docs/api-reference/create-next-app#options)
- [npm init using](https://ar.al/2021/04/01/npm-init-using/)
- [Vite/degit](https://vitejs.dev/guide/#community-templates)
- etc.
There is also https://github.com/stoplightio/dev-portal/tree/plugin but DnC didn't create it and it would need more documentation in place before suggesting it to new users.
I have [a PoC](https://github.com/stoplightio/elements-template) to test some of these other options but it's broken and needs more work.
For now this documentation update will at least not immediately give errors for new users of `elements`.

Update docs to pin create-react-app to 4.0.3 when using elements templates

---

packages/elements-dev-portal/package.json
packages/elements-dev-portal/src/containers/StoplightProject.tsx

If a node's name is changed, we will automatically redirect to the new node slug.
- Fixes https://github.com/stoplightio/platform-internal/issues/10770

fix(StoplightProject): handle redirect to node slug

---

demo/package.json
packages/elements-core/package.json
packages/elements-dev-portal/package.json
packages/elements/package.json

Pushing a version bump for issue 10336 (PR that's already merged was 2093)

chore: bumping version after elements-core update

---

demo/package.json
packages/elements-core/package.json
packages/elements-dev-portal/package.json
packages/elements/package.json

Fix to table borders in markdown-viewer; need to update to point to the new package and bump elements versions to create new package.

chore: update markdown-viewer versions and bump elements versions

---

packages/elements-core/package.json
packages/elements-core/src/components/Docs/HttpOperation/Badges.tsx
packages/elements-core/src/components/Docs/HttpService/ServerInfo.tsx
packages/elements-core/src/components/NonIdealState.tsx
packages/elements-core/src/components/TryIt/Response/Response.tsx
packages/elements-core/src/components/TryIt/TryIt.tsx
packages/elements-dev-portal/package.json
packages/elements-dev-portal/src/components/UpgradeToStarter.tsx
packages/elements/package.json
yarn.lock

- bumps FA to v6
- bumps mosaic, markdown-viewer, and JSV to latest for FA v6
- bundles the handful of FA icons being used so that downstream consumers do not run into FA tree-shaking issues (particularly in CJS environments)

feat: bump fontawesome to v6

---

packages/elements-core/package.json
packages/elements-core/src/components/Docs/Docs.tsx
packages/elements-core/src/components/Docs/Model/Model.tsx
packages/elements-core/src/components/Docs/TwoColumnLayout.tsx
packages/elements-core/src/components/ResponseExamples/ResponseExamples.tsx
packages/elements-core/src/hooks/useIsCompact.ts
packages/elements-core/src/index.ts
packages/elements-dev-portal/package.json
packages/elements-dev-portal/src/components/NodeContent/NodeContent.tsx
packages/elements-dev-portal/src/version.ts
packages/elements/package.json
setupTests.ts

**elements-core**
- Adds a `layoutOptions.compact` prop to `Docs` to control when `Model` is in single vs two column layout
- Adds a copy button to `Model` examples
**elements-dev-portal**
- Adds a `compact` option to `NodeContent` to be passed down to the `Docs` component above
```ts
/**
* Provide a number to trigger compact mode when the component is within that pixel width,
* or a boolean to enable or diable compact mode.
* @default false
* @example 600
*/
compact?: number | boolean;
```
---

feat(elements-dev-portal): add compact option to NodeContent component

---

packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.tsx
packages/elements-core/src/hooks/__tests__/useChosenServerUrl.ts.spec.ts
packages/elements-core/src/hooks/useChosenServerUrl.ts

Aside from a fix, I also did it so that a single click selects the whole url.
https://user-images.githubusercontent.com/9273484/184356301-73afd1b5-c8ff-49d5-9691-04837e65b9d8.mp4

fix(elements-core): display operation path correctly at all times

---

packages/elements/src/components/API/APIWithSidebarLayout.tsx
packages/elements/src/containers/API.tsx

Fixes https://github.com/stoplightio/elements/issues/2205
When `HashRouter` is used, hashes are (obviously) used for navigation.
This poses an issue, as h2/h3/h4 headings may also contain anchors, which are supposed to navigate us to a particular fragment of the page.
Currently elements redirects you to root (`/`) if a given route has no node associated.
Due to the nature of `HashRouter`, both the heading anchors and the links adhere to the same mechanism, thus any link heading that's not associated with a subpage, will be redirected to `/`
Unfortunately, we cannot quite tell whether a user wants to navigate to a particular subpage or simply has an anchor, so what I ended up was: if we cannot associate any node with a particular hash, we redirect to `/` and keep the initial hash.
This way …

fix(elements): keep unresolvable hashes when hash router is used

---

demo/package.json
packages/elements-core/package.json
packages/elements-core/src/components/RequestSamples/__tests__/RequestSamples.test.tsx
packages/elements-core/src/components/TryIt/build-request.ts
packages/elements-dev-portal/package.json
packages/elements/package.json
yarn.lock

Fixes missing data property for javascript/fetch request sample for multipart/form-data requests with attached file.
Generated code snippet didn't include form data in fetch options. It was fixed in the newest version of `httpsnippet`. 
Before:
After:

fix: multipart form-data request samples

---

demo/package.json
packages/elements-core/package.json
packages/elements-core/src/components/LinkHeading.tsx
packages/elements-core/src/context/RouterType.tsx
packages/elements-dev-portal/package.json
packages/elements/package.json

Follow up to https://github.com/stoplightio/elements/pull/2237
We can't use `useLocation` if we're not in the context of the react router provider. Verified fixed the issue over in platform, and the tests from the above PR still pass.

fix: do not use custom link heading if no router

---

demo/package.json
packages/elements-core/package.json
packages/elements-core/src/components/TryIt/TryIt.tsx
packages/elements-dev-portal/package.json
packages/elements-dev-portal/src/version.ts
packages/elements/package.json

Addresses: https://github.com/stoplightio/platform-internal/issues/11697
Continuation of https://github.com/stoplightio/elements/pull/2061
Large TryIt responses are causing a bug that prevents response component to rerender correctly making old response content persist (despite the `response` state set with new data). 
I wasn't able to find the reason for that, even going deep into mosaic CodeViewer component - new props are passed and can be accessed correctly.
Solution to that issue (not the greatest one) is resetting the `response` state ~~after invoking request~~ before setting actual response, which causes the CodeViewer to unmount and render again once new response is set. ~~That causes slight change in the ui making old response disappear on invoking new request. That's something …

fix: try it large responses

---

.circleci/config.yml
packages/elements-dev-portal/package.json
packages/elements-dev-portal/src/components/NodeContent/NodeContent.tsx

fix(elements-dev-portal): link hover text

---

demo/package.json
packages/elements-core/package.json
packages/elements-core/src/components/Docs/Sections.tsx
packages/elements-core/src/core.css
packages/elements-dev-portal/package.json
packages/elements/package.json

Addresses https://github.com/stoplightio/platform-internal/issues/10150
Adds horizontal scrolling for http operation responses.
I'm not adding `x-overflow` property directly to mosaic because:
- it has some side effects with wrapping whitespaces 
- mosaic is supposed to handle overflowing tabs by switching them to select component (though it may require good bit of work)
- elements response tabs is the only case when we need that
https://user-images.githubusercontent.com/14196079/200484922-62e122e6-a5af-4b6c-9380-4e4ce280b941.mov

feat: response tabs horizontal scrolling

---

packages/elements-core/src/utils/exampleGeneration/exampleGeneration.ts

#2238 
Fix for 2238, large example schemas throwing "Exceeds schema size error massage". Fix should allow for larger sized response and example schemas. 
The fix was to increase the tick count for the json schema sampler. By default the tick count is set to 1000. For elements I am now passing in a count of 6000. For context the schema the kicked off this issue has around 30,000 lines and requires around 4500 ticks. 
Impacts. Ticks are used as a count ceiling for performance and dose not increase execution time. Added by https://github.com/stoplightio/json-schema-sampler/pull/22 . It appears ticks might not be a great indicator of time/performance. For context the sampler execution timer is exponential but only averages around 8ms for the large schema mentioned above. I think we need a …

fix: increase tick count for json schema sampler

---

packages/elements-core/package.json
packages/elements-core/src/components/Docs/HttpOperation/Body.tsx
packages/elements-core/src/components/Docs/HttpOperation/Parameters.tsx
packages/elements-core/src/components/Docs/HttpOperation/Responses.tsx
packages/elements-core/src/components/Docs/Model/Model.tsx
packages/elements-core/src/components/MarkdownViewer/CustomComponents/CodeComponent.tsx
packages/elements-core/src/context/InlineRefResolver.spec.tsx
packages/elements-core/src/context/InlineRefResolver.tsx
packages/elements-dev-portal/package.json
packages/elements/package.json

Needed for https://github.com/stoplightio/platform-internal/issues/11538
Given
```json
{
"openapi": "3.0.0",
"paths": {
"/user": {
"post": {
"requestBody": {
"content": {
"application/json": {
"schema": {
"type": "object",
"properties": {
"user": {
"$ref": "#/components/schemas/User"
}
}
}
}
}
}
}
}
},
"components": {
"schemas": {
"User": {
"type": "object",
"nullable": true,
"properties": {
"id": {
"type": "integer",
"nullable": true
},
"stars": {
"type": "number",
"format": "int32"
}
}
}
}
}
}
```
Before:
After:

fix(elements-core): translate resolved schema objects

---

docs/getting-started/elements/elements-options.md

Updates the "Elements Configuration Options" documentation to include `hideSchemas`, `hideExport`
- `hideSchemas` was introduced in https://github.com/stoplightio/elements/pull/1430
- `hideExport` was introduced in https://github.com/stoplightio/elements/pull/1652

chore(docs): Update elements configuration options

---

packages/elements-dev-portal/package.json

This mostly makes sure we the new packages uses the latest elements.
The current one points at ~7.7.5 and is potentially 5 releases behind

chore: release elements-dev-portal

---

packages/elements-core/src/components/RequestSamples/__tests__/__snapshots__/convertRequestToSample.spec.ts.snap
packages/elements-core/src/components/RequestSamples/__tests__/convertRequestToSample.spec.ts

In a bid to solve https://github.com/stoplightio/elements/issues/2282 https://github.com/stoplightio/elements/issues/2141, I'm thinking to switch from `httpsnippet` (which doesn't seem to be actively maintained based on the release schedule) to a more frontend-friendly maintained fork of it, namely `@readme/httpsnippet`.
Let's add some tests so that the output is more or less the same once we make the update.
This may also potentially help reduce the size of the entire elements-core bundle.

test(elements-core): snapshot example code examples

---

packages/elements-core/src/components/TryIt/Parameters/parameter-utils.spec.ts
packages/elements-core/src/components/TryIt/Parameters/parameter-utils.ts

Fix for https://github.com/stoplightio/platform-internal/issues/15773
With it yalc'd into platform-internal using the provided spec in the ticket:

fix: schema property examples are no longer incorrectly arrays

---

packages/elements-core/src/components/TryIt/TryIt.spec.tsx
packages/elements-core/src/components/TryIt/build-request.spec.ts
packages/elements-core/src/components/TryIt/build-request.ts

Closes https://github.com/stoplightio/elements/issues/1798

Add Content-Type and Accept headers where necessary

---

packages/elements-dev-portal/src/components/NodeContent/NodeContent.tsx
packages/elements-dev-portal/src/types.ts

adds support for more specific export urls in dev portal.

feat(elements-dev-portal): support new node links for export

---

packages/elements-core/src/__fixtures__/operations/security-basic.ts
packages/elements-core/src/__fixtures__/operations/security-bearer.ts
packages/elements-core/src/components/TryIt/Auth/Auth.tsx
packages/elements-core/src/components/TryIt/TryIt.spec.tsx

when switching between different operations that have distinct security schemes, the try it box would retain an invalid scheme. this simply resets it instead of trying to remember all instances of it.

fix(core): reset the auth in tryit to a supported scheme

---

packages/elements-core/package.json
packages/elements-core/src/__fixtures__/articles/schema-with-refs.ts
packages/elements-core/src/components/MarkdownViewer/CustomComponents/CodeComponent.tsx
packages/elements-core/src/components/MarkdownViewer/MarkdownViewer.spec.tsx
packages/elements-dev-portal/package.json
packages/elements/package.json

Fixes resolving refs in markdown files.
`Docs` component uses `InlineRefResolverProvider` referencing parsed document. That works fine with json/yaml files but in case of markdown it results in undefined document and resolver (since markdown file is not a plain object). We need to point to the schema document instead of whole markdown file. 
This PR adds internal `InlineRefResolverProvider` to `CodeComponent` to handle schemas within markdown files.

fix(elements-core): markdown ref resolving

---

packages/elements-core/package.json
packages/elements-dev-portal/package.json
packages/elements/package.json
yarn.lock

Addresses [#12516](https://app.zenhub.com/workspaces/-team-enchilotters-62ab7d6627416c001df37493/issues/gh/stoplightio/platform-internal/12516)

fix: bump json-schema-viewer to show array[$ref] descriptions

---

packages/elements/package.json
packages/elements/src/utils/oas/__tests__/oas.spec.ts
packages/elements/src/utils/oas/index.ts

Fixes the issue when a OpenAPI specification file has a url such as `/entries/{id}/data)` the `findMapMatch`-function
throws a `invalid regular expresison` error.

fix: handle keys which have uncommon url paths, such as `/entries/{id}/data)`

---

packages/elements-dev-portal/package.json
packages/elements-dev-portal/src/components/Search/Search.stories.tsx
packages/elements-dev-portal/src/components/Search/Search.tsx
packages/elements-dev-portal/src/index.ts
packages/elements-dev-portal/src/version.ts

https://github.com/stoplightio/elements/assets/58235624/394bb2d9-b2f8-45bd-9349-e07a2810df06
This is an example of the `SearchResults` component embedded into the search sidebar in ninja.  
I basically extracted the search results into its own component so that it can be shown anywhere (doesn't have to be in a modal).  
This is how it looks in storybook: 
https://github.com/stoplightio/elements/assets/58235624/63eea696-01aa-415e-88b2-566009178736

feat(elements-dev-portal): embedded search component

---

demo/package.json
packages/elements-core/package.json
packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.stories.ts
packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.tsx
packages/elements-core/src/components/Docs/HttpOperation/Responses.tsx
packages/elements-dev-portal/package.json
packages/elements/package.json

Adding responsiveness to Docs `HttpOperation`:
- Adds `compact` property and usage of `useIsCompact` hook to `HttpOperation`
- Moves `TryIt` panel to left column for compact layout
- Adds modal instead of tab responses for compact layout
https://github.com/stoplightio/elements/assets/14196079/cf20cac7-07b0-4158-9213-9a56c4737cea

feat: responsive http operation

---

packages/elements-core/package.json
packages/elements-core/src/components/MosaicTableOfContents/TableOfContents.tsx
packages/elements-core/src/components/MosaicTableOfContents/constants.ts
packages/elements-core/src/components/MosaicTableOfContents/types.ts
packages/elements-dev-portal/package.json
packages/elements-dev-portal/src/components/Search/Search.stories.tsx
packages/elements-dev-portal/src/components/TableOfContents/TableOfContents.stories.tsx
packages/elements-dev-portal/src/components/TableOfContents/TableOfContents.tsx
packages/elements/package.json

I went ahead and made this a minor version change since it's not a bug fix, but if it should be versioned differently, please let me know!
As you will see, the icons are not the [desired](https://www.figma.com/file/BZZk7EIPmOEzKfn4TE5psF/Docs-Enhancements-2023?type=design&node-id=928-8593&mode=design&t=u4NLUp6ntgJI2C1N-0) 'far' [prefix](https://fontawesome.com/docs/web/add-icons/how-to#classic-family), and I don't know the best way to make this work with the way elements is configured. If this is a blocker, I do need some help figuring it out. 
@noor-ahmad tagging you here and adding you as a reviewer to give your thoughts on the icon issue. 
This PR changes the style of the project ToC in the following ways: 
- Icons are all on the left side of the items on screens of all sizes
- When …

Feat: Project ToC Responsive Style Adjustments

---

packages/elements-core/package.json
packages/elements-core/src/components/Docs/HttpOperation/Responses.tsx
packages/elements-dev-portal/package.json
packages/elements-dev-portal/src/version.ts
packages/elements/package.json

Updated response code components on workspace docs page with attributes to make them easy to find for testing

fix: update responsive components to be test friendly

---

packages/elements-core/package.json
packages/elements-core/src/components/Docs/HttpOperation/Responses.tsx
packages/elements-core/src/components/Docs/Sections.tsx
packages/elements-dev-portal/package.json
packages/elements/package.json

Addresses #[18159](https://app.zenhub.com/workspaces/-team-enchilotters-62ab7d6627416c001df37493/issues/gh/stoplightio/platform-internal/18159)

chore: consistent dropdown

---

packages/elements-core/package.json
packages/elements-core/src/components/Docs/HttpService/HttpService.stories.ts
packages/elements-core/src/components/Docs/HttpService/HttpService.tsx
packages/elements-core/src/components/Docs/Model/Model.stories.tsx
packages/elements-core/src/components/Docs/Model/Model.tsx
packages/elements-dev-portal/package.json
packages/elements/package.json
yarn.lock

Hides the export button for a compact layout in http service and modal components.
https://github.com/stoplightio/elements/assets/14196079/aadbcc68-3a2f-41be-bec3-1da42e50e80a

fix: mobile export button

---

packages/elements-dev-portal/package.json
packages/elements-dev-portal/src/containers/StoplightProject.tsx

Reproducing bug (if you go to a branch that is NOT the default branch and has a '/' in it stoplight project will break):
https://github.com/stoplightio/elements/assets/58235624/77464eaa-b14b-4e17-810b-47a65baaf216
After fix:
https://github.com/stoplightio/elements/assets/58235624/c887087d-ba11-47ae-b23b-d41cfd55615f

Fix: stoplight project branch bug

---

packages/elements/package.json
packages/elements/src/components/API/APIWithStackedLayout.tsx
packages/elements/src/containers/API.spec.tsx

Addresses https://github.com/stoplightio/elements/issues/2415

Fix: stacked layout path

---

packages/elements/package.json
packages/elements/src/index.ts

Exports `transformOasToServiceNode` and `useExportDocumentProps` functions to let users transform oas documents and use internal elements components independently (SwaggerHub Portal use case).

feat: export oas utils

---

packages/elements/package.json
packages/elements/src/components/API/APIWithStackedLayout.tsx
packages/elements/src/index.ts

Context: https://smartbear.slack.com/archives/C05T7G43M0B/p1700213734193029
Adds export of `APIWithStackedLayout` component to `elements` package.
Adds `showPoweredByLink` property to `APIWithStackedLayout`

chore: export stacked layout

---

packages/elements/package.json
packages/elements/src/components/API/APIWithStackedLayout.tsx
packages/elements/src/containers/API.tsx

Motivtion: 
Using `APIWithStackedLayout` component externaly without react router usage that causes compatibility issues
Changes:
- Moves `useLocation` call from `APIWithStackedLayout` to `Api`
- adds `location` property to `APIWithStackedLayout` component
- fixes comparing location hash with item name

feat: stacked layout location property

---

packages/elements-core/src/components/Docs/HttpOperation/Parameters.tsx

To avoid confusion for published OAS 2.0 docs, we want to hide the query parameter Style field if it is `unspecified`.

fix: unspecified field is undefined

---

demo/package.json
packages/elements-core/package.json
packages/elements-core/src/__fixtures__/operations/put-todos.ts
packages/elements-core/src/components/Docs/HttpOperation/Body.tsx
packages/elements-core/src/components/Docs/HttpOperation/Callbacks.tsx
packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.spec.tsx
packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.tsx
packages/elements-core/src/components/Docs/HttpOperation/Request.tsx
packages/elements-core/src/components/Docs/HttpOperation/Responses.tsx
packages/elements-dev-portal/package.json
packages/elements/package.json

Addresses: https://github.com/stoplightio/platform-internal/issues/18498
Adds callbacks to `HttpOperation`
https://github.com/stoplightio/elements/assets/14196079/6f82650f-2c18-4d80-8d4f-27932cbf9f18

feat: callbacks

---

packages/elements-core/src/components/TryIt/TryIt.tsx

fixes #2467. multiple copies of the server list caused this to render out of control. the server id should allow us to keep it in sync

fix(tryit): stop re-render of try-it

---

packages/elements-core/src/components/MosaicTableOfContents/TableOfContents.tsx
packages/elements-dev-portal/src/containers/StoplightProject.tsx

when using elements-dev-portal and the hash router, a custom toc with slugs would result in a broken page. this fixes the route matching and makes the routes absolute

fix(dev-portal): fix broken hash router links

---

packages/elements-core/package.json
packages/elements-dev-portal/package.json
packages/elements/package.json
yarn.lock

Bumps json schema viewer. See https://github.com/stoplightio/json-schema-viewer/pull/248
Needed for  https://app.zenhub.com/workspaces/-team-honey-hackers-62ab7d6627416c001df37493/issues/gh/stoplightio/platform-internal/12705

fix: array child pattern match validation

---

packages/elements-dev-portal/package.json
packages/elements-dev-portal/src/__fixtures__/branches.json
packages/elements-dev-portal/src/components/BranchSelector/BranchSelector.spec.tsx
packages/elements-dev-portal/src/components/BranchSelector/BranchSelector.stories.tsx
packages/elements-dev-portal/src/containers/StoplightProject.tsx
packages/elements-dev-portal/src/handlers/getBranches.ts
packages/elements-dev-portal/src/types.ts

Fixes [STOP-94](https://smartbear.atlassian.net/browse/STOP-94)
Fixes rendering two `StoplightProject` components due to matching both routes.
The API for `listBranches` has changed for elements-dev-portal v2 introducing slightly different response format. 
It still responds with previous data structure for all elements-dev-portal v1 instances so its users are not affected.
Changes:
- updates response data type to follow new format
- adds Switch to router to prioritize rules - currently `/:nodeSlug+` rule matches all paths (because of `+` sign)
[STOP-87]: https://smartbear.atlassian.net/browse/STOP-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[STOP-94]: https://smartbear.atlassian.net/browse/STOP-94?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …

fix: branch selector

---

packages/elements-core/package.json
packages/elements-core/src/index.ts
packages/elements/package.json
packages/elements/src/components/API/__tests__/utils.test.ts
packages/elements/src/components/API/utils.ts

Addresses: [STOP-22](https://smartbear.atlassian.net/browse/STOP-22)
In `elements` package we are grouping operations and webhooks separately under their categories.
This PR adds grouping models under Schemas category so it stays consistent with others.
[STOP-22]: https://smartbear.atlassian.net/browse/STOP-22?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(elements): group models under schemas category

---

packages/elements-core/package.json
packages/elements-dev-portal/package.json
packages/elements/package.json
yarn.lock

Bumps scripts package to address the following dependabot security alerts:
- https://github.com/stoplightio/elements/security/dependabot/128
- https://github.com/stoplightio/elements/security/dependabot/103

chore: bump scripts version

---

package.json
yarn.lock

Addresses security vulnerability in `v2.2.1` in `json5`

chore: bump ts-jest

---

packages/elements-dev-portal/package.json
yarn.lock

Addresses security vulnerability in `v3.0.4` in `minimatch` package

chore: bump replace package to 1.2.2

---

package.json
packages/elements-core/package.json
packages/elements-dev-portal/package.json
packages/elements/package.json
yarn.lock

Removes the following dependencies:
- `semantic-release` `v19.0.0`
- `axios` `v0.21.1`
- `ip` `v2.0.0`

chore: upgrade dependencies

---

packages/elements-core/package.json
packages/elements-core/src/components/Docs/HttpService/HttpService.spec.tsx
packages/elements-core/src/components/TryIt/Response/Response.spec.tsx
packages/elements/package.json
yarn.lock

Removes `jest-enzyme` that is not supported anymore and includes vulnerable `jsdom`

chore: remove jest-enzyme

---

docs/getting-started/elements/angular.md

Just a small typo in angular guide.

Fix CUSTOM_ELEMENTS_SCHEMA name

---

demo/package.json
packages/elements-core/package.json
packages/elements-dev-portal/package.json
packages/elements/package.json
yarn.lock

json-schema-viewer version updated for binary format
[STOP-464](https://smartbear.atlassian.net/browse/STOP-464)
[STOP-464]: https://smartbear.atlassian.net/browse/STOP-464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: bump json-schema-viewer 

---

packages/elements-core/src/components/TryIt/TryIt.tsx

This PR removes the unnecessary rounded style from the "TryIt" response area.
https://github.com/stoplightio/elements/assets/761462/13debea3-a8ed-4493-a5d2-95866c193262

fix: remove the unnecessary rounded style

---

packages/elements-core/package.json
packages/elements-core/src/components/TableOfContents/constants.ts
packages/elements-core/src/constants.ts
packages/elements-dev-portal/package.json
packages/elements/package.json

STOP-477 
- Verbs on Docs page are not colored (OPTIONS, HEAD, TRACE). Added background color for these methods.

fix: background colors added for trace, options and head method

---

packages/elements-core/package.json
packages/elements-core/src/utils/__tests__/securitySchemes.spec.ts
packages/elements-core/src/utils/securitySchemes.ts
packages/elements-dev-portal/package.json
packages/elements/package.json
yarn.lock

The PR displays security scheme roles in the API security section: https://github.com/stoplightio/elements/issues/2491
I also did changes in [http-spec](https://github.com/stoplightio/http-spec/pull/268), so the version needs to be bumped as well. I will do this as soon as the other PR is merged and released.

feat: display security scheme roles

---

packages/elements-core/package.json
packages/elements-core/src/components/TryIt/Parameters/ParameterEditor.tsx
packages/elements-core/src/components/TryIt/Parameters/parameter-utils.spec.ts
packages/elements-core/src/components/TryIt/Parameters/parameter-utils.ts
packages/elements-core/src/components/TryIt/TryIt.spec.tsx
packages/elements-dev-portal/package.json
packages/elements/package.json

PR change placeholder for selectable values with default value to `defaults to: {defaultValue}` https://github.com/stoplightio/elements/issues/2585
---

feat: default boolean schema value is not shown in parameters dropdown

---

demo/package.json
packages/elements-core/package.json
packages/elements-dev-portal/package.json
packages/elements-dev-portal/src/version.ts
packages/elements/package.json
yarn.lock

This is fix for https://github.com/stoplightio/elements/issues/2655.
There were mismatches in versions of `@stoplight/mosaic` and `@stoplight/mosaic-code-editor`/`@stoplight/mosaic-code-viewer`. Someone has bumped mosaic, but forgot to bump code-editor and code-viewer. Still not sure why it caused the issue with inverted colours (the changes are not related at all), but bumping all versions fixed the issue locally. Let's see if it will work in preview.

chore(deps): Bump @stoplight/mosaic, @stoplight/mosaic-code-editor and @stoplight/mosaic-code-viewer

---

packages/elements-dev-portal/package.json
packages/elements-dev-portal/src/components/NodeContent/NodeContent.tsx

[STOP-955](https://smartbear.atlassian.net/browse/STOP-955)
Handled URL based on domain matching
Have checked jest and manual testing.
[STOP-955]: https://smartbear.atlassian.net/browse/STOP-955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: STOP-955 handling open URL based on domain name

---

packages/elements-core/package.json
packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.tsx
packages/elements-dev-portal/package.json
packages/elements/package.json
yarn.lock

STOP-979
Fixed the Extra newline added when copying URLs from documentation and bumping the Elements version
Tested on Local Env.
I have copied URL from here 
when I pasted this URL, It is breaking into 2 parts
Same URL pasted after the fix, It is working as expected.

fix:copy paste URL & bumping the Elements versions

---

packages/elements-core/src/components/Docs/HttpService/AdditionalInfo.tsx

Currently renders undefined if no license has been provided

FIX: Do not render undefined when license has not been defined

---

package.json
yarn.lock

sec: resolve @stoplight/react-error-boundary to v3

---

packages/elements-core/package.json
packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.tsx
packages/elements-core/src/utils/ref-resolving/resolvedObject.test.ts
packages/elements-core/src/utils/ref-resolving/resolvedObject.ts
packages/elements-dev-portal/package.json
packages/elements/package.json

[STOP-1027](https://smartbear.atlassian.net/browse/STOP-1027)
Previously, if not logged in, the schema which is marked internal showing up in dropdown as an empty 'object' for oneOf/anyOf in public docs.
In case of every schema is internal in the list it will display the error message.
[STOP-1027]: https://smartbear.atlassian.net/browse/STOP-1027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: internal schema apprears as object on logout

---

packages/elements-core/src/components/Docs/HttpService/AdditionalInfo.stories.ts
packages/elements-core/src/components/Docs/HttpService/AdditionalInfo.tsx
packages/elements-core/src/components/Docs/HttpService/HttpService.spec.tsx

This PR addresses [the issue](https://github.com/stoplightio/elements/issues/2711) , where the `AdditionalInfo` component prioritizes the license identifier (SPDX) over the provided license URL. [According to the OpenAPI specification](https://spec.openapis.org/oas/latest.html#license-object), the url and identifier fields in the license object are **mutually exclusive**, meaning that if both are provided, the `license.url` should take precedence.
I updated the logic in the `AdditionalInfo` component to make sure that **if a `license.url` is provided, it takes precedence over the `license.identifier`**. In the case where only an identifier is available, the component falls back to using the SPDX license URL.
Following is the change to the license URL logic:
```ts
const licenseUrl = …
```

Fix license URL vs identifier precedence issue in AdditionalInfo component

---

packages/elements-core/package.json
yarn.lock

[STOP-231](https://smartbear.atlassian.net/browse/STOP-231)
Previously range was getting displayed without being defined in the schema for int64. solved this issue in json-schema-viewer.
[STOP-231]: https://smartbear.atlassian.net/browse/STOP-231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(deps): Bump json-schema-viever from 4.16.1 to 4.16.3

---

packages/elements-dev-portal/package.json
packages/elements-dev-portal/src/components/NodeContent/NodeContent.spec.tsx
packages/elements-dev-portal/src/components/NodeContent/NodeContent.tsx

STOP-1073
fixed the issue of Devportal Links between the article.
I have tested it manually and also tested in the platform-internal using Yalc.
https://github.com/user-attachments/assets/b11584a8-5cb5-422e-96f2-f8c81ee0f5ce
https://github.com/user-attachments/assets/f3a033de-8b83-43df-b9ef-8407c2f67578

fix: issue of internal and exterrnal links in article

---

packages/elements-core/package.json
packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.tsx
packages/elements-dev-portal/package.json
packages/elements/package.json

fix: Fix Leading / in Empty Paths Rendering for Elements View

---

examples/react-cra/package.json

fix: fix react-cra typescript error

---

packages/elements-core/package.json
packages/elements-core/src/components/Docs/HttpOperation/Body.tsx
packages/elements-core/src/components/Docs/HttpOperation/LazySchemaTreePreviewer.tsx
packages/elements-core/src/components/Docs/HttpOperation/Responses.tsx
packages/elements-core/src/components/Docs/HttpService/HttpService.tsx
packages/elements-core/src/components/Docs/Model/Model.tsx
packages/elements-dev-portal/package.json
packages/elements-dev-portal/src/version.ts
packages/elements/package.json

Doc viewer mask data is not reflecting on page, when nests model properties are masked
[STOP-2697](https://smartbear.atlassian.net/browse/STOP-2697?atlOrigin=eyJpIjoiYmU3MzEzMjhhMmE2NGJmZmJiMDZkY2ZiZWUxMjUwMDQiLCJwIjoiaiJ9)
Current Behavior: 
Doc viewer mask properties of design library  is not reflecting on page with new approach
Expected Behavior: 
It was tested locally by changing mask properties assigned at request, responses and models from studio editor.
[STOP-2820]: https://smartbear.atlassian.net/browse/STOP-2820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[STOP-2697]: https://smartbear.atlassian.net/browse/STOP-2697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Stop 2417 hide button

---

packages/elements-core/package.json
packages/elements-core/src/components/Docs/HttpOperation/LazySchemaTreePreviewer.tsx
packages/elements-core/src/components/Docs/HttpOperation/Responses.tsx
packages/elements-core/src/components/Docs/TwoColumnLayout.tsx
packages/elements-dev-portal/package.json
packages/elements/package.json

[STOP-2847](https://smartbear.atlassian.net/browse/STOP-2847)
[STOP-2847](https://smartbear.atlassian.net/browse/STOP-2847)
[STOP-2796](https://smartbear.atlassian.net/browse/STOP-2796)
[STOP-2859](https://smartbear.atlassian.net/browse/STOP-2859)
Current Behavior: 
Mask properties of design library are not reflecting on Studio preview and doc viewer page with new approach
Masking not working at deep nested level for request, response and for local models.
Masking not working for array of objects
Required is not functioning 
Expected Behavior: 
Mask properties of design library must reflect on Studio preview and doc viewer page with new approach
[STOP-2847]: https://smartbear.atlassian.net/browse/STOP-2847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …

Stop 2417 hide docs
