stoplightio/elements

packages/elements/src/components/API/SidebarLayout.tsx
=> fix: scrollbar being in the wrong place

packages/elements/src/components/TryIt/TryIt.spec.tsx, packages/elements/src/components/TryIt/TryIt.tsx
=> feat: prettify try it json response

demo/package.json, examples/angular/package.json, examples/angular/yarn.lock, lerna.json, packages/elements-utils/package.json, packages/elements/package.json, yarn.lock
=> release: 7.0.0-beta.1

packages/elements/src/containers/API.stories.tsx
=> chore: add API sidebar layout story to Storybook

packages/elements/src/components/MarkdownViewer/CustomComponents/CodeComponent.spec.ts, packages/elements/src/components/MarkdownViewer/CustomComponents/CodeComponent.tsx, packages/elements/src/components/MarkdownViewer/CustomComponents/CodeWithSchemaViewer.tsx, packages/elements/src/components/MarkdownViewer/CustomComponents/Provider.tsx, packages/elements/src/components/MarkdownViewer/MarkdownViewer.spec.tsx
Closes: https://github.com/stoplightio/elements/issues/836
Note: The actual change is in http part of `CodeComponent` that can be seen in first commit. GH doesn't detect file rename here unfortunately.
=> feat: Embed TryIt in Articles

.circleci/config.yml
Fixes releasing on every commit issue
=> fix: release

packages/elements-dev-portal/package.json
=> chore: remove private field from dev-portal package.json

packages/elements-dev-portal/README.md, packages/elements/README.md
=> chore: basic readme for dev-portal package

packages/elements/src/__fixtures__/services/without-origin.ts, packages/elements/src/components/Docs/HttpService/__tests__/index.spec.tsx, packages/elements/src/components/TryIt/build-request.ts, packages/elements/src/utils/http-spec/IServer.ts
=> fix: prepend origin to urls without it

package.json, packages/elements-core/src/__fixtures__/operations/with-url-variables.ts, packages/elements-core/src/components/TryIt/TryIt.spec.tsx, packages/elements-core/src/components/TryIt/build-request.ts
Resolves: #1260 
Also, brings back the whole test suite 😬
=> Fix: Server URL path is removed when sending request 

packages/elements-core/src/web-components/createElementClass.ts, packages/elements/src/web-components/__stories__/Api.stories.tsx
=> fix: web components fixed height layout

packages/elements-core/src/components/TryIt/TryItWithRequestSamples.spec.tsx, packages/elements-core/src/components/TryIt/build-request.ts
=> Fix: basePath missing in request samples 

examples/angular/yarn.lock, examples/react-cra/yarn.lock, examples/react-gatsby/yarn.lock, packages/elements-core/package.json, yarn.lock
=> chore: upgrade jsv to beta.17

packages/elements-core/package.json, packages/elements-core/src/components/Docs/HttpOperation/Parameters.tsx, packages/elements-core/src/styles/_HttpOperation.scss, packages/elements/src/containers/API.stories.tsx, yarn.lock
Resolves: #1092 
UPDATE: ~~⚠️ This does not apply to `Response` section~~ It will after merging https://github.com/stoplightio/json-schema-viewer/pull/146
=> feat(Docs): Markdown support in Parameters descriptions

packages/elements-dev-portal/src/index.ts
Relates to https://github.com/stoplightio/platform-internal/issues/6255
We need the provider to alter URL of API to - for example - facilitate the local testing.
=> feat: export dev portal provider

package.json
Hopefully resolves #1330 
I can't tell you why this works. I tried it in SSH and it did. Simply editing `.npmrc` doesn't do the trick for some reason, this does.
=> chore: fix automated release

packages/elements/src/containers/API.tsx
Resolves #837 
As indicated in the issue, pretty much everything is covered already. This makes the error message a bit nicer, but that's it.
=> feat: better copy for errors

packages/elements-core/src/components/Docs/Model/Model.spec.tsx, packages/elements-core/src/components/Docs/Model/Model.tsx, packages/elements-core/src/utils/exampleGeneration.ts
=> feat(docs): examples for standalone schemas

.circleci/config.yml, cypress/integration/api.ts, cypress/integration/stoplight-project.ts, cypress/plugins/index.js, cypress/support/commands.js, cypress/support/index.d.ts, examples/static-html/index.html, examples/static-html/package.json, examples/static-html/serve-files.js, examples/static-html/stoplight-project/index.html, examples/static-html/zoom-api/index.html, package.json
Resolves #969 
I had to write a custom script to run this weird dual-SPA site, but that doesn't change the fact that the HTMLs should just load as is.
=> feat: add static html example

demo/package.json, packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements/package.json
Closes #1384 
Versions: 
- @stoplight/elements-demo@7.0.0-beta.4
- @stoplight/elements-core@7.0.0-beta.8
- @stoplight/elements-dev-portal@1.0.0-beta.2
- @stoplight/elements-utils@7.0.0-beta.2
- @stoplight/elements@7.0.0-beta.5
=> chore(release): publish new beta

packages/elements-core/src/components/TryIt/MockingButton.tsx
Fixes #1304 
https://user-images.githubusercontent.com/7916523/121526221-76acae00-c9f9-11eb-9119-544e160a1153.mov
EDIT:
Distance between buttons:
=> fix: mocking button when enabled

packages/elements/src/components/Docs/HttpOperation/Parameters.tsx, packages/elements/src/components/Docs/HttpOperation/__tests__/index.spec.tsx
A part of: https://github.com/stoplightio/platform-internal/issues/5372
=> fix(Docs): docs crashing when viewing endpoint

packages/elements-core/src/components/Docs/HttpOperation/Parameters.tsx, packages/elements-core/src/components/Docs/Sections.tsx
=> fix: align jsv and parameters

release.sh
Resolves #1417 
Porting the fix from v7/master. Hopefully this fixes the v6 release.
=> fix: fix v6 release

examples/angular/package.json, examples/angular/yarn.lock
Bumps all deps in the angular example.
Resolves security warnings.
=> chore: bump angular deps

examples/react-cra/package.json, examples/react-cra/yarn.lock, examples/react-gatsby/package.json, examples/react-gatsby/yarn.lock
=> chore: update elements in examples

packages/elements/src/components/API/APIWithSidebarLayout.tsx, packages/elements/src/components/API/__tests__/utils.test.ts, packages/elements/src/components/API/utils.ts, packages/elements/src/containers/API.tsx
=> feat: hide schemas in toc

packages/elements-core/src/index.ts, packages/elements-core/src/web-components/createElementClass.ts, packages/elements-dev-portal/src/web-components/components.ts, packages/elements/src/web-components/components.ts
=> fix: web components props typings & actual configs

packages/elements-core/src/components/MosaicTableOfContents/TableOfContents.spec.tsx, packages/elements-dev-portal/src/components/TableOfContents/TableOfContents.tsx, packages/elements-dev-portal/src/containers/StoplightProject.tsx, packages/elements-dev-portal/src/web-components/components.ts
Closes #1370 
Before:
After (with option turned on):
=> feat: add option to collapse toc

demo/package.json, packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements/package.json
=> Release/elements beta.6 and dev portal beta.3

examples/angular/package.json, examples/angular/yarn.lock, examples/react-cra/package.json, examples/react-cra/yarn.lock, examples/react-gatsby/package.json, examples/react-gatsby/yarn.lock
=> chore: update elements packages in examples

examples/react-cra/package.json, examples/react-cra/yarn.lock, examples/react-gatsby/package.json, examples/react-gatsby/yarn.lock
=> chore: remove mobx from examples

packages/elements-dev-portal/package.json, packages/elements-dev-portal/src/components/NodeContent/NodeContent.tsx
We need to be able to hide whole panel as well in platform
=> feat: node content hide try it panel

README.md, docs/getting-started/dev-portal/react.md, docs/getting-started/integrations/react.md
=> chore: add docs about templates

packages/elements-dev-portal/package.json, yarn.lock
Needed for platform.
Bumps elements-core in dev-portal and triggers release.
=> feat(dev portal): bump core

demo/package.json, package.json, packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements-utils/package.json, packages/elements/package.json, yarn.lock
- @stoplight/elements-demo@7.0.0
- @stoplight/elements-core@7.0.0
- @stoplight/elements-dev-portal@1.0.0
- @stoplight/elements-utils@7.0.0
- @stoplight/elements@7.0.0
=> chore(release): publish stable versions

examples/angular/package.json, examples/bootstrap/index.html, examples/bootstrap/project.html, examples/react-cra/package.json, examples/react-gatsby/package.json, examples/static-html/stoplight-project/index.html, examples/static-html/zoom-api/index.html
=> chore: update elements packages in examples to stable

packages/elements-core/package.json, yarn.lock
=> fix: docs crashing in cra

docs/getting-started/dev-portal/gatsby.md, docs/getting-started/integrations/gatsby.md, toc.json
Closes #1270 
As a part of this PR please also test the starters and go through their code.
=> chore: add documentation about gatsby starters

cypress/integration/api.ts, cypress/integration/stoplight-project.ts
Fixes https://github.com/stoplightio/elements/issues/1398
Adds bunch of missing e2e tests.
=> test: enhance e2e suite

packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements/package.json
Releases fix for https://github.com/stoplightio/elements/issues/1526
https://github.com/stoplightio/elements/pull/1563 got merged before we agreed we can do such releases within PR
=> fix: release badges fix

README.md, cypress/support/commands.js, docs/getting-started/dev-portal/web-component.md, docs/getting-started/usage/web-component.md, docs/guides/hello-world.md, packages/elements-core/package.json
We've been stable a while but didnt update the docs. Oops!
=> chore: use stable version

packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements/package.json
elements-core 7.1.6
elements 7.0.4
elements-dev-portal 1.0.6
=> chore: release elements-core 7.1.6

packages/elements-dev-portal/src/components/NodeContent/NodeContent.tsx, packages/elements-dev-portal/src/version.ts
Fixes: https://github.com/stoplightio/platform-internal/issues/7098
=> fix: relative links

demo/package.json, packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements/package.json
- @stoplight/elements-demo@7.0.1
- @stoplight/elements-core@7.1.7
- @stoplight/elements-dev-portal@1.0.7
- @stoplight/elements@7.0.5
fix: scroll on toc click (#1597) 
fix: relative links (#1598)
=> chore(release): publish

packages/elements-core/package.json, packages/elements-core/src/hoc/withQueryClientProvider.tsx, packages/elements-dev-portal/package.json
Related to https://github.com/stoplightio/platform-internal/issues/7001
=> fix: reduce react query cache time

packages/elements-core/package.json
Releasing core with changes from #1633
=> chore(release): core release

packages/elements-core/src/hoc/withQueryClientProvider.tsx, yarn.lock
Resolves #1452
**Before**
https://user-images.githubusercontent.com/58433203/126804407-eb2d3344-984b-400e-869a-1fea09e82bb8.mov
**After**
https://user-images.githubusercontent.com/58433203/126804376-b9e8c6a0-6d55-4efa-82d2-82fe616a8f71.mov
=> feat: don't retry failed requests

packages/elements-core/src/components/TryIt/TryIt.spec.tsx, packages/elements-core/src/components/TryIt/build-request.ts, yarn.lock
Resolves: #1606 
**Before**
**After**
=> fix: uppercase request method

packages/elements/src/components/API/APIWithSidebarLayout.tsx, packages/elements/src/components/API/utils.ts, yarn.lock
A part of: #1615 
It makes the API component show HTTP Service page at all times, even if there is not description in it (in contrary to the previous behavior)
Doing the same but in `StoplightProject` will happen in https://github.com/stoplightio/platform-internal/pull/7266
**Screenshots**
https://user-images.githubusercontent.com/58433203/126777828-3c6e2433-30a2-4ddc-80cd-48d0acf794d3.mov
=> fix: always show overview page in API component

packages/elements-core/src/components/Docs/HttpService/HttpService.tsx
=> feat: single column overview page

packages/elements-core/src/components/Docs/HttpOperation/Badges.tsx, packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.spec.tsx, packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.tsx, packages/elements-core/src/components/Docs/HttpService/SecuritySchemes.tsx, packages/elements-core/src/components/TryIt/Auth/Auth.tsx, packages/elements-core/src/components/TryIt/TryIt.spec.tsx, packages/elements-core/src/utils/oas/security.ts, yarn.lock
Fixes: https://github.com/stoplightio/elements/issues/1588
Shows security keys for auth schemes that occur duplicated.
Unique schemes:
Duplicated schemes:
=> feat: same type security schemes

packages/elements-core/src/__fixtures__/services/petstore.ts, packages/elements-core/src/__fixtures__/services/with-unnamed-servers.ts, packages/elements-core/src/__fixtures__/services/with-url-variables.ts, packages/elements-core/src/__fixtures__/services/without-origin.ts, packages/elements-core/src/components/Docs/HttpService/HttpService.spec.tsx, packages/elements-core/src/components/Docs/HttpService/ServerInfo.tsx, packages/elements-dev-portal/src/version.ts
=> feat: display multiple servers in service overview page

packages/elements-dev-portal/src/__fixtures__/node-content.json, packages/elements-dev-portal/src/index.ts, packages/elements-dev-portal/src/types.ts
Needed by: https://github.com/stoplightio/platform-internal/issues/7356
Adds 2 more properties to `Node` type.
=> chore: node type

packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements/package.json
- @stoplight/elements-core@7.1.13
- @stoplight/elements-dev-portal@1.0.11
- @stoplight/elements@7.0.8
chore: bump mosaic version (#1681)
feat: In MarkdownViewer TryIt, parse path parameters based on provided url (#1684)
feat: choose server in tryit (#1680)
=> chore: release

packages/elements-core/src/components/TryIt/Parameters/ParameterEditor.tsx
this is Will's version of #1703
=> Fix: TryIt in Markdown has too large font

packages/elements/src/components/API/APIWithStackedLayout.tsx
Up for discussion/testing.
I've noticed that stacked layout was getting quite slow recently, so I made an optimisation attempt.
If we can validate that it doesn't have any serious regressions, I would encourage to merge it. ;)
=> chore: optimize stacked layout

README.md
We've got this on Prism and Spectral, let's get it up on Elements too.
=> Link to the Ecologi forest

packages/elements-core/src/components/Docs/HttpService/ServerInfo.tsx
=> feat: server url copy button

packages/elements-core/src/components/MosaicTableOfContents/TableOfContents.tsx
Addresses https://github.com/stoplightio/elements/issues/1714
=> chore: add bold font weight to TOC component

packages/elements-core/src/components/MarkdownViewer/CustomComponents/Provider.tsx, packages/elements-core/src/components/MarkdownViewer/index.tsx, packages/elements-dev-portal/src/version.ts
=> chore: swap custom markdown provider for official one

packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements-dev-portal/src/version.ts, packages/elements/package.json
Releases:
- elements-core: 7.3.2
- elements: 7.3.2
- elements-dev-portal: 1.3.0
Changes:
- Feat/hide internal operations (#1739)
- chore: swap custom markdown provider for official one (#1754)
=> chore: release elements

packages/elements-core/src/components/Docs/HttpService/ServerInfo.tsx
Addresses https://github.com/stoplightio/elements/issues/1746
=> fix: copy mock server url

packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements-dev-portal/src/version.ts, packages/elements/package.json
Releases:
- elements-core: 7.3.3
- elements: 7.3.3
- elements-dev-portal: 1.3.1
Changes:
- [feat (dev-portal): add search component #1749](https://github.com/stoplightio/elements/pull/1749)
- [Search JS Element Documentation Example #1765](https://github.com/stoplightio/elements/pull/1765)
- [fix: copy mock server url #1760](https://app.zenhub.com/workspaces/-team-pierogi-platoon-610871b8d6e5310013071b72/issues/stoplightio/elements/1760)
=> chore: release elements 7.3.3

packages/elements/src/components/API/__tests__/utils.test.ts, packages/elements/src/components/API/utils.ts, yarn.lock
Addresses #1805 
If a group does not contain any items (possible if all the items are x-internal and hideInternal flag is true) do not render the group.
=> fix: don't render groups that have no items

docs/getting-started/dev-portal/web-component.md
Fixed typos reported by sales.
=> Fixed typos

packages/elements-core/package.json, yarn.lock
Addresses https://github.com/stoplightio/platform-internal/issues/7717
=> fix(json-schema-viewer): bump json-schema-viewer for new ui changes

demo/index.html, demo/package.json, demo/src/components/DemoNavbar.tsx, yarn.lock
Just fixing the github star button on the demo page.
=> chore(demo): fix GH star button

packages/elements-core/src/__fixtures__/operations/put-todos.ts, packages/elements-core/src/components/TryIt/Parameters/parameter-utils.spec.ts, packages/elements-core/src/components/TryIt/Parameters/parameter-utils.ts, packages/elements-core/src/components/TryIt/TryIt.spec.tsx
Fixes https://github.com/stoplightio/platform-internal/issues/8990
=> fix(TryIt): prefer default value over example value

demo/package.json, packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements/package.json
Includes the sticky TOC fix #1913
=> chore: release 7.5.1

demo/package.json, packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements/package.json
This release process is awkward, we should automate it.
We already have circleci setup: https://github.com/stoplightio/elements/blob/14f3cd8f2c87508aaaeca8813c47b181f3f9dafd/.circleci/config.yml#L102
=> release: elements-core@7.5.4 and elements-dev-portal@1.6.4

.github/PULL_REQUEST_TEMPLATE/release.md, .github/pull_request_template.md
Based on: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
=> chore(pr template): add basic release PR template

packages/elements-core/src/components/MarkdownViewer/CustomComponents/ReactRouterLink.tsx, packages/elements-core/src/hoc/withRouter.tsx, packages/elements-dev-portal/src/containers/StoplightProject.tsx
- Fixes an issue introduced by https://github.com/stoplightio/elements/pull/1867#discussion_r791128167
- Fixes https://github.com/stoplightio/elements/issues/1980
=> fix(elements-dev-portal): use react-router-dom link

packages/elements-core/src/components/Layout/SidebarLayout.tsx
Fixes #1997 
Urgent-ish, as it completely locks the page from scrolling.
=> fix: locked scroll

packages/elements-dev-portal/package.json, packages/elements-dev-portal/src/consts.ts, packages/elements-dev-portal/src/handlers/__tests__/getNodes.test.ts, packages/elements-dev-portal/src/handlers/getNodes.ts, packages/elements-dev-portal/src/hooks/useGetNodes.ts
Integrated here https://github.com/stoplightio/platform-internal/pull/10535
=> fix(elements-dev-portal): useGetNodes does not accept branch

packages/elements-core/src/components/TryIt/Response/Response.tsx
=> fix: corrected spelling error: occured -> occurred

toc.json
Fixed issue with missing config topics in TOC
=> added options files to toc

packages/elements-core/package.json, packages/elements-core/src/components/MosaicTableOfContents/TableOfContents.tsx, packages/elements-core/src/components/MosaicTableOfContents/utils.ts, packages/elements-dev-portal/package.json, packages/elements-dev-portal/src/handlers/getNodeContent.ts
Small adjustments to prep for the upcoming stable IDs + custom paths release.
=> feat(dev-portal): prep stable ids + custom paths

demo/package.json, packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements/package.json
- [ x] Read [`CONTRIBUTING.md`](../CONTRIBUTING.md)
- [ x] [Read the release section of `CONTRIBUTING.md`](../CONTRIBUTING.md#releasing-elements)
=> chore(release): elements-core@7.5.17, elements@7.5.17, elements-dev-portal@1.7.1

.circleci/config.yml, demo/package.json, packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements/package.json, yarn.lock
Just bumping version of json-schema-viewer
=> chore: bump-json-schema-viewer

.gitignore, docs/getting-started/dev-portal/dev-portal-options.md, docs/getting-started/elements/elements-options.md
Added missing option to Elements options and Elements Dev Portal options topics; added Stoplight Style Guide files to gitignore.
=> Added tryIt credential policy

.stoplight.json, toc.json
---
Adding the CONTRIBUTING.md file to `toc.json`, similar to what we have done for [Prism](https://github.com/stoplightio/prism/commit/05954339b134256b50f7231137e6f5c820499c40).
=> docs: add contributing guide to toc

demo/package.json, packages/elements-core/package.json, packages/elements-core/src/components/MosaicTableOfContents/TableOfContents.tsx, packages/elements-dev-portal/package.json, packages/elements-dev-portal/src/types.ts, packages/elements/package.json
=> fix: react when TableOfContents maxDepthOpenByDefault prop changes

demo/package.json, packages/elements-core/package.json, packages/elements-core/src/components/Docs/HttpOperation/Parameters.spec.tsx, packages/elements-core/src/components/Docs/HttpOperation/Parameters.tsx, packages/elements-dev-portal/package.json, packages/elements/package.json
Needed for https://github.com/stoplightio/platform-internal/issues/13230
=> fix(elements-core): handle invalid schemas in params

CONTRIBUTING.md
Closes #2227.
I also ran CONTRIBUTING through Grammarly and fixed some grammar issues.
=> docs(repo): update node version in contributing guidelines

.circleci/config.yml, packages/elements-core/src/components/TryIt/build-request.spec.ts, packages/elements-core/src/components/TryIt/build-request.ts
https://github.com/stoplightio/platform-internal/issues/13653
=> fix(core): use param delimiter for arrays in TryIt

docs/getting-started/elements/elements-options.md
Referenced resizeable sidebar based on this issue: https://github.com/stoplightio/elements/pull/2268
=> Modified docs/getting-started/elements/elements-options.md

docs/getting-started/dev-portal/dev-portal-options.md, docs/getting-started/elements/elements-options.md, docs/guides/great-api-docs.md
Derek's feedback from this PR: https://github.com/stoplightio/elements/pull/2290
=> Derek feedback

packages/elements-core/package.json, packages/elements-core/src/context/InlineRefResolver.spec.tsx, packages/elements-core/src/context/InlineRefResolver.tsx, packages/elements-dev-portal/package.json, packages/elements/package.json
Fixes https://github.com/stoplightio/elements/issues/2310
=> fix(elements-core): circular $refs in schemas no longer work

docs/elements-vs-dev-portal.md, docs/getting-started/dev-portal/dev-portal-angular.md, docs/getting-started/dev-portal/dev-portal-options.md, docs/getting-started/dev-portal/html.md, docs/getting-started/dev-portal/react.md, docs/getting-started/elements/elements-options.md
Changed cross-project links from meta to docs
=> switched meta links to docs

packages/elements-core/package.json, packages/elements-core/src/index.ts, packages/elements/package.json
Needed by https://github.com/stoplightio/elements/pull/2329
=> chore(elements-core): expose RouterTypeContext

packages/elements-dev-portal/package.json, packages/elements-dev-portal/src/containers/StoplightProject.tsx
Related to https://github.com/stoplightio/elements/issues/2323
Needs elements-core@7.0.11 https://github.com/stoplightio/elements/pull/2330
This doesn't fix TOC. It only fixes headings such as the one in the screenshot below
=> fix(dev-portal): set RouterTypeContext

packages/elements-dev-portal/src/components/NodeContent/NodeContent.tsx
=> feat: add export request to node content

packages/elements-core/package.json, packages/elements-core/src/components/Docs/Article/index.tsx, packages/elements/package.json, yarn.lock
Fixes the issue with toc navigation in #2323
=> fix(elements-core): toc links yield 404 when using hash router

packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements/package.json
=> chore: release 7.7.14

packages/elements-core/package.json, packages/elements-core/src/__fixtures__/services/petstore.ts, packages/elements-core/src/__fixtures__/services/with-url-variables.ts, packages/elements-core/src/components/Docs/HttpService/HttpService.spec.tsx, packages/elements-core/src/components/Docs/HttpService/ServerInfo.tsx, packages/elements-core/src/components/TryIt/TryIt.tsx, packages/elements-core/src/utils/http-spec/IServer.ts, packages/elements-core/src/utils/http-spec/__tests__/IServer.spec.ts, packages/elements-dev-portal/package.json, packages/elements/package.json, tsconfig.json, yarn.lock
=> feat(elements-core): display server variables

packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements/package.json
=> chore: bump version

examples/react-cra/src/components/Navigation.tsx, packages/elements-core/src/__fixtures__/operations/put-todos.ts, packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.spec.tsx, packages/elements-core/src/components/TryIt/Auth/Auth.tsx, packages/elements-core/src/components/TryIt/Auth/authentication-utils.ts, packages/elements-core/src/components/TryIt/TryIt.spec.tsx, packages/elements-core/src/components/TryIt/TryIt.tsx, packages/elements-core/src/components/TryIt/build-request.ts, packages/elements-core/src/utils/oas/security.ts
Closes https://github.com/stoplightio/elements/issues/2395
- [ X] Read [`CONTRIBUTING.md`](../CONTRIBUTING.md)
- [ X] [Read the release section of `CONTRIBUTING.md`](../CONTRIBUTING.md#releasing-elements)
=> feat(try-it): add AND security support

packages/elements-core/package.json, packages/elements-core/src/components/Docs/HttpOperation/Request.tsx, packages/elements-dev-portal/package.json, packages/elements/package.json
Release version 7.13.0 - support AND authentication in TryIt and HttpOperation components
=> chore: release 7.13.0

packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements-dev-portal/src/version.ts, packages/elements/package.json, yarn.lock
Bumps JSV that adds complex arrays top row validations
=> fix: complex array top row validations

packages/elements/src/utils/oas/__tests__/oas.spec.ts
=> chore(tests): unused securities are filtered out of overview

demo/package.json, packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements-dev-portal/src/version.ts, packages/elements/package.json
Bump version and release fixes to include suggested values for security.
=> chore: version bump 7.13.4 and 1.16.4

packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements/package.json
Follow up to https://github.com/stoplightio/elements/pull/2426
=> Chore: release 7.13.7

lerna.json, package.json, yarn.lock
upgrades lerna to fix dependencies
=> chore(deps): upgrade to lerna 7

demo/package.json, packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements/package.json, yarn.lock
Bumps [mosaic](https://github.com/stoplightio/mosaic/pull/438) that fixes select component for React 18
=> fix: select focus

packages/elements-core/package.json, packages/elements/package.json
=> Chore/release 7.15.2

.github/workflows/jira-issue-label-added.yaml
=> New jira label workflow: Create jira-issue-label-added.yaml

demo/README.md, packages/elements-core/package.json, packages/elements-core/src/index.ts, packages/elements-dev-portal/package.json, packages/elements-dev-portal/src/components/NodeContent/NodeContent.tsx, packages/elements-dev-portal/src/version.ts, packages/elements/package.json
Fixes: https://github.com/stoplightio/platform-internal/issues/18708
https://github.com/stoplightio/elements/assets/19455540/2229b774-7a3f-4614-a9c0-16321c200ccf
=> fix(linkheader):  anchor links not found

cypress/integration/stoplight-project.ts, packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements/package.json, yarn.lock
=> fix(deps): upgrade http-spec and lodash

demo/src/constants.ts
I've been working on the Train Travel API as a cracking replacement for the Pet Store API, and it looks great in Elements. Also fixed the Box link.
In general, make sure you have:
=> Fixed box, added train travel & museum

packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements/package.json, yarn.lock
- Bumps scripts package
- Bumps ansi-regex resolved version
=> chore: upgrade dependencies

packages/elements-core/package.json, packages/elements/package.json, yarn.lock
=> chore: bump http-spec

demo/package.json, packages/elements-core/package.json, packages/elements-core/src/components/Layout/MobileTopNav.tsx, packages/elements-core/src/components/Layout/ResponsiveSidebarLayout.tsx, packages/elements-core/src/styles.css, packages/elements-dev-portal/package.json, packages/elements/package.json, packages/elements/src/containers/API.stories.tsx, yarn.lock
=> chore: bump mosaic

.github/workflows/jira-issue-label-added.yaml
=> chore: use reusable jira workflow

.github/workflows/jira-issue-label-added.yaml
=> chore: add team based on repo

.github/workflows/jira-issue-label-added.yaml
=> chore: add maintenance team

.github/workflows/jira-issue-label-added.yaml
=> Update prism jira action workflow with new team name (elements edition)

packages/elements-core/package.json, packages/elements-core/src/components/RequestSamples/convertRequestToSample.ts, packages/elements-core/src/components/TryIt/TryItWithRequestSamples.spec.tsx, packages/elements-core/src/components/TryIt/build-request.ts, packages/elements-dev-portal/package.json, packages/elements/package.json
https://github.com/stoplightio/elements/issues/2352
=> feat: add brackets around default URL parameters

package.json, yarn.lock
https://smartbear.atlassian.net/browse/STOP-705
Before fix Total vulnerabilities 49
after fix Total vulnerabilities 40
**TESTING:**
Tested all use cases and dependencies locally.
=> chore(dev-deps): resolved ws vulnerabilities

package.json, yarn.lock
=> add fast-xml-parser and tar resolutions to resolve dependabot issues

packages/elements-core/package.json, packages/elements-dev-portal/package.json, packages/elements/package.json
STOP-979
version update for code change to fix the issue  Extra newline added when copying URLs from documentation.
Tested in Local Env.
=> bump element-core version

packages/elements-core/package.json, packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.tsx, packages/elements-dev-portal/package.json, packages/elements/package.json
[STOP-979](https://smartbear.atlassian.net/browse/STOP-979)
Revert the changes of Copy Paste Issue.
Have checked jest and manual testing.
[STOP-979]: https://smartbear.atlassian.net/browse/STOP-979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> revert the  changes of copy paste issue

packages/elements-core/package.json, packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.tsx, packages/elements-dev-portal/package.json, packages/elements/package.json
STOP-979
The previous fix works for Chrome but not for Safari.
=> Previous fix works for Chrome but not for Safari.

packages/elements-core/package.json, packages/elements-core/src/hoc/withQueryClientProvider.tsx, packages/elements-dev-portal/package.json, packages/elements/package.json
Schema body link returns to top option
[STOP-1212](https://smartbear.atlassian.net/browse/STOP-1212?atlOrigin=eyJpIjoiYmU3MzEzMjhhMmE2NGJmZmJiMDZkY2ZiZWUxMjUwMDQiLCJwIjoiaiJ9)
When you select an option from the dropdown for Body it stays selected for 10-15 seconds and then reverts to the top option. 
It was tested locally by changing the stale time from 15 sec to 5 min.
[STOP-1212]: https://smartbear.atlassian.net/browse/STOP-1212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Stop 1212 fix schema body returns top

packages/elements-core/package.json, packages/elements-core/src/components/Docs/HttpOperation/HttpOperation.spec.tsx, packages/elements-core/src/components/RequestSamples/convertRequestToSample.ts, packages/elements-dev-portal/package.json, packages/elements-dev-portal/src/version.ts, packages/elements/package.json
Schema body link returns to top option
[STOP-2564](https://smartbear.atlassian.net/browse/STOP-2564?atlOrigin=eyJpIjoiYmU3MzEzMjhhMmE2NGJmZmJiMDZkY2ZiZWUxMjUwMDQiLCJwIjoiaiJ9)
Current Behavior: 
The cURL command generated by Stoplight uses the --data flag for form data parameters, even when the Content-Type is set to application/x-www-form-urlencoded in the OpenAPI definition.
example: --data 'client_secret=***'
Expected Behavior: 
The generated cURL command should use the --data-urlencode flag for form data parameters when the Content-Type is application/x-www-form-urlencoded, in order to properly encode the data.
example: --data-urlencode 'client_secret=***'
It was tested locally by changing the stale time from 15 sec to 5 min.
Before fix
After fix
[STOP-1212]: …
=> Fixed cURL issue
